// 24x24 colour weather icons for the header. Generated by tools/gen_weather_icons.py - do not edit.
#pragma once
#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif
extern const lv_image_dsc_t wx_sun;
extern const lv_image_dsc_t wx_moon;
extern const lv_image_dsc_t wx_cloud_sun;
extern const lv_image_dsc_t wx_cloud_moon;
extern const lv_image_dsc_t wx_cloud;
extern const lv_image_dsc_t wx_rain;
extern const lv_image_dsc_t wx_showers;
extern const lv_image_dsc_t wx_snow;
extern const lv_image_dsc_t wx_fog;
extern const lv_image_dsc_t wx_storm;
#ifdef __cplusplus
}
#endif
