#!/usr/bin/env python3
"""Embed the pinned root CAs for the HTTPS prototype (DESIGN.md 2.1) as firmware/src/app/tls_roots.cpp.

Usage:
    tools/gen_tls_roots.py [--out firmware/src/app/tls_roots.cpp] ROOT.pem [ROOT.pem ...]

Each PEM must be a single root certificate. The generated file carries, per root, the subject, the
key type and the notAfter date as a comment (read with `openssl x509`), so a reviewer can see what
the device trusts without decoding anything, and a wrong file (an intermediate, a leaf) is caught by
the CA:TRUE check below rather than by a failed handshake on the device.

Why a generator and not hand-pasted PEM: the roots will need swapping when a data source changes
CA (DESIGN.md 2.1 "rotation risk"); re-running this with the new root is one command and produces a
reviewable diff. The mapping host -> root lives in tls_roots.h (pinnedRootsForHost), not here.

Defaults, as verified 2026-09-16 (`openssl s_client -showcerts`, then `openssl verify` against each
single root with the default store disabled - the served chains validate with exactly these):
    www3.septa.org                        -> Amazon Root CA 1   (RSA 2048, expires 2038-01-17)
    api.open-meteo.com                    -> ISRG Root X1       (RSA 4096, expires 2035-06-04)
    bts-status.bicycletransit.workers.dev -> GTS Root R4        (ECDSA P-384, expires 2036-06-22)
On a Debian/Ubuntu host these are /etc/ssl/certs/{Amazon_Root_CA_1,ISRG_Root_X1,GTS_Root_R4}.pem.
"""
import argparse
import os
import subprocess
import sys


def x509_field(pem_path, *args):
    out = subprocess.run(["openssl", "x509", "-in", pem_path, "-noout", *args], capture_output=True, text=True, check=True)
    return out.stdout.strip()


def describe(pem_path):
    subject = x509_field(pem_path, "-subject").replace("subject=", "", 1)
    end = x509_field(pem_path, "-enddate").replace("notAfter=", "", 1)
    text = x509_field(pem_path, "-text")
    key = "unknown key"
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("Public Key Algorithm:"):
            key = s.split(":", 1)[1].strip()
        elif s.startswith("Public-Key:"):
            key += " " + s.split(":", 1)[1].strip()
        elif s.startswith("ASN1 OID:"):
            key += " " + s.split(":", 1)[1].strip()
    if "CA:TRUE" not in text:
        sys.exit(f"{pem_path}: not a CA certificate (no CA:TRUE basic constraint) - refusing to pin it")
    return subject, key, end


def c_ident(subject):
    cn = subject.split("CN = ")[-1].split(",")[0]
    return "k" + "".join(ch if ch.isalnum() else "_" for ch in cn.title().replace(" ", ""))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "firmware", "src", "app", "tls_roots.cpp"))
    ap.add_argument("pems", nargs="+")
    a = ap.parse_args()

    roots = []
    for pem in a.pems:
        with open(pem) as f:
            body = f.read().strip()
        if body.count("-----BEGIN CERTIFICATE-----") != 1:
            sys.exit(f"{pem}: expected exactly one certificate")
        subject, key, end = describe(pem)
        roots.append((c_ident(subject), subject, key, end, body))

    lines = [
        "// GENERATED by tools/gen_tls_roots.py - do not edit by hand; re-run it with the new PEM to rotate a root.",
        "// Pinned root CAs for the HTTPS prototype (DESIGN.md SS2.1). Only compiled with -DTRANSIT_HTTPS: without the",
        "// flag this file contributes nothing, so the shipping image is byte-identical to before it existed.",
        "#ifdef TRANSIT_HTTPS",
        '#include "tls_roots.h"',
        "",
        "namespace transit_app {",
        "namespace tls_roots {",
        "",
    ]
    for ident, subject, key, end, body in roots:
        lines.append(f"// {subject}")
        lines.append(f"// {key}; not after {end}")
        lines.append(f"const char {ident}[] =")
        pem_lines = body.splitlines()
        for i, pl in enumerate(pem_lines):
            end_tok = ";" if i == len(pem_lines) - 1 else ""
            lines.append(f'    "{pl}\\n"{end_tok}')
        lines.append("")
    lines += ["}  // namespace tls_roots", "}  // namespace transit_app", "#endif  // TRANSIT_HTTPS", ""]
    with open(a.out, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {a.out}: {len(roots)} roots, {sum(len(r[4]) for r in roots)} PEM bytes")
    for ident, subject, key, end, _ in roots:
        print(f"  {ident}: {subject} | {key} | expires {end}")


if __name__ == "__main__":
    main()
