#include "web_server.h"

#include <Arduino.h>
#include <ChunkPrint.h>  // ESPAsyncWebServer's per-chunk Print sink, see sendJsonStreamed()
#include <ESPAsyncWebServer.h>
#include <LittleFS.h>
#include <Update.h>
#include <WiFi.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <cctype>
#include <cstring>
#include <ctime>
#include <memory>
#include <new>

#include "auth.h"
#include "config_store.h"
#include "cxx_exception_pool.h"
#include "demo_data.h"
#include "net_poller.h"
#include "weather_service.h"
#include "ui/ui.h"
#include <esp_heap_caps.h>
#include <esp_ota_ops.h>
#include <esp_system.h>  // esp_reset_reason() for /api/state's last_restart (DESIGN.md SS12.1)
#include "bike_service.h"
#include "profiles.h"
#include "proxy_worker.h"
#ifdef TRANSIT_HTTPS
#include "http_fetch.h"  // transport stats for /api/state (DESIGN.md SS2.1)
#endif
#include "sd_logger.h"
#include "transit_core/rail_stations.h"

// Generated by web/build.mjs from web/ (DESIGN.md SS10): WEB_ASSETS[] (path, content_type,
// gzipped PROGMEM bytes, length), WEB_ASSETS_COUNT, and WEB_ASSETS_ETAG (see registerWebAssets()
// below). Guarded so this file still compiles in the (now purely historical) case the generated
// header is missing.
#if __has_include("generated/web_assets.h")
#include "generated/web_assets.h"
#define TRANSIT_HAVE_WEB_ASSETS 1
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "unknown"
#endif
#ifndef BOARD_NAME
#define BOARD_NAME "unknown"
#endif

using transit::Alert;
using transit::Arrival;
using transit::Snapshot;
using transit::Status;
using transit::StopSnapshot;

namespace transit_app {

namespace {

AsyncWebServer g_server(80);

const char *statusToString(Status s) {
  switch (s) {
    case Status::Live:
      return "live";
    case Status::Scheduled:
      return "scheduled";
    case Status::Skipped:
      return "skipped";
    case Status::Unknown:
    default:
      return "unknown";
  }
}

// DESIGN.md SS7's Arrival object shape.
void serializeArrival(const Arrival &a, JsonObject o, transit::Epoch now) {
  o["trip"] = a.trip;
  o["vehicle"] = a.vehicle;
  o["destination"] = a.destination;
  o["predicted"] = a.predicted;
  o["scheduled"] = a.scheduled;
  o["eta_s"] = a.effective() > 0 ? (a.effective() - now) : 0;
  o["late_min"] = a.late_min;
  o["late_known"] = a.late_known;
  o["status"] = statusToString(a.status);
  o["seats"] = a.seats;
  o["sched_trip"] = a.sched_trip;  // matched static-schedule trip id, "" when unmatched (DESIGN.md SS7)
}

// transit::Health as the wire token GET /api/state uses (model.h, DESIGN.md SS4.7/SS7).
const char *healthToString(transit::Health h) {
  switch (h) {
    case transit::Health::Live:
      return "live";
    case transit::Health::ScheduleOnly:
      return "schedule_only";
    case transit::Health::Stale:
      return "stale";
    case transit::Health::Unavailable:
    default:
      return "unavailable";
  }
}

// `cfg` is the caller's copy of the active config (handleGetState already holds one): the web UI
// titles each panel from its fields, so they are echoed next to the live data. Taking it by
// reference rather than copying again keeps a second Config (eight stops of std::strings) out of
// the request's peak (SS12.1).
void serializeSnapshot(const Snapshot &snap, const Config &cfg, JsonObject out) {
  transit::Epoch now = (transit::Epoch)time(nullptr);
  JsonArray stops = out["stops"].to<JsonArray>();
  for (const StopSnapshot &s : snap.stops) {
    JsonObject so = stops.add<JsonObject>();
    so["key"] = s.key;
    for (const transit::StopConfig &sc : cfg.stops) {
      if (sc.key != s.key) continue;
      so["mode"] = sc.mode == transit::Mode::Rail ? "rail" : sc.mode == transit::Mode::Subway ? "subway" : sc.mode == transit::Mode::Trolley ? "trolley" : "bus";
      so["route"] = sc.route;
      so["stop_id"] = sc.stop_id;
      so["station"] = sc.station;
      so["direction"] = sc.direction;
      so["headsign"] = sc.headsign;
      so["label"] = sc.label;
      so["stop_name"] = sc.stop_name;
      so["show"] = sc.show;
      break;
    }
    so["ok"] = s.ok;
    so["error"] = s.error;
    so["health"] = healthToString(s.health);
    so["source_ts"] = s.source_ts;  // when SEPTA produced the data; 0 = the feed carried no timestamp
    so["source_age_s"] = s.source_ts > 0 ? (int64_t)(now - s.source_ts) : (int64_t)-1;
    so["weather_note"] = stopWeatherNote(s.key, s.arrivals.empty() ? 0 : s.arrivals.front().effective());
    JsonArray arrivals = so["arrivals"].to<JsonArray>();
    for (const Arrival &a : s.arrivals) {
      serializeArrival(a, arrivals.add<JsonObject>(), now);
    }
  }
  // DESIGN.md SS4.8/SS7: the main location's conditions plus the hourly slots the notes use.
  WeatherView wv = getWeather();
  JsonObject weather = out["weather"].to<JsonObject>();
  weather["enabled"] = cfg.weather.enabled;  // the config, not the last poll: a save applies at once
  weather["units"] = wv.fahrenheit ? "f" : "c";
  weather["age_s"] = wv.age_s;  // main location's last SUCCESS, millis-based, -1 = never (F29)
  weather["stale"] = wv.stale;  // over 60 min old: the device suppresses the header icon and notes
  if (cfg.weather.enabled && wv.main.valid()) {
    JsonObject m = weather["main"].to<JsonObject>();
    m["temp"] = wv.main.temp;
    m["feels_like"] = wv.main.feels_like;
    m["code"] = wv.main.code;
    m["text"] = weather::codeText(wv.main.code);
    m["wind"] = wv.main.wind;
    JsonArray hours = m["hours"].to<JsonArray>();
    for (const weather::Hour &h : wv.main.hours) {
      JsonObject ho = hours.add<JsonObject>();
      ho["t"] = h.epoch;
      ho["code"] = h.code;
      ho["text"] = weather::codeText(h.code);
      ho["prob"] = h.precip_prob;
      ho["temp"] = h.temp;
    }
  }
  int prof = activeProfileIndex(cfg, (time_t)now);
  out["active_profile"] = prof >= 0 ? cfg.profiles[(size_t)prof].name : "";
  BikeView bv = getBikes();
  JsonObject bike = out["bike"].to<JsonObject>();
  bike["enabled"] = cfg.bike.enabled;
  bike["age_s"] = bv.fetched_epoch > 0 ? (int64_t)now - (int64_t)bv.fetched_epoch : -1;
  JsonArray bstations = bike["stations"].to<JsonArray>();
  // In config order, with counts from the last fetch when that station was part of it; a station
  // added a moment ago shows -1 until the poller catches up rather than being missing.
  for (const BikeStation &cs : cfg.bike.stations) {
    if (!cfg.bike.enabled) break;
    indego::Station st;
    st.id = cs.id;
    st.name = cs.name;
    for (const indego::Station &f : bv.stations) {
      if (f.id == cs.id) {
        st = f;
        if (st.name.empty()) st.name = cs.name;
        break;
      }
    }
    JsonObject so = bstations.add<JsonObject>();
    so["id"] = st.id;
    so["name"] = st.name;
    so["bikes"] = st.bikes;
    so["ebikes"] = st.ebikes;
    so["classic"] = st.classic;
    so["docks"] = st.docks;
    so["total_docks"] = st.total_docks;
    so["active"] = st.active;
  }
  JsonArray alerts = out["alerts"].to<JsonArray>();
  for (const Alert &al : snap.alerts) {
    if (!cfg.alerts) break;  // the config, not the last poll
    JsonObject ao = alerts.add<JsonObject>();
    ao["route"] = al.route;
    ao["text"] = al.text;
    ao["current"] = al.current;
    JsonArray detours = ao["detours"].to<JsonArray>();
    for (const std::string &d : al.detours) {
      detours.add(d);
    }
  }
}

void sendJson(AsyncWebServerRequest *request, int code, JsonDocument &doc) {
  // Under memory pressure (several concurrent requests on a ~65 KB heap) ArduinoJson silently
  // truncates the document and String silently stays empty; both used to go out as an empty
  // HTTP 200. A 503 lets the web UI keep the last good state and try again on its next poll.
  String body;
  bool ok = !doc.overflowed() && serializeJson(doc, body) > 0 && body.length() > 0;
  if (!ok) {
    request->send(503, "application/json", "{\"error\":\"out of memory building the response, retry\"}");
    return;
  }
  request->send(code, "application/json", body);
}

// DESIGN.md SS12.1 "zero-copy": the heavy responses (/api/state, /api/config) do not go through
// sendJson(). The document is MOVED, not copied, into a holder the chunked response owns, and
// serialised straight into each TCP send chunk as the socket drains (the filler re-walks the
// document per chunk, skipping what was already sent - the same ChunkPrint ESPAsyncWebServer's own
// AsyncJsonResponse uses). So the response holds the document plus one 2 x MSS send buffer - not,
// as sendJson() costs, the document plus a String of the whole body plus AsyncBasicResponse's own
// copy of that String, which needed a body-sized contiguous block twice at the worst moment.
// Chunked transfer encoding, so there is no measuring pass and no Content-Length; every client this
// device has (the web app's fetch(), curl, the device suite) handles that. Deliberately NOT used for
// the small responses: their String is a few dozen bytes, while any chunked response allocates the
// 2.9 KB send buffer (nothrow, retried on the next poll), which is the wrong trade for
// /api/debug/ui, the endpoint the suite uses to watch the device while it is starved. Same overflow
// rule as sendJson(): a truncated document is a 503, never an empty or partial 200. Why
// AsyncJsonResponse itself is not used: it costs two more ArduinoJson serializer instantiations
// (its ChunkPrint-typed fill and measureJson's counting pass, ~2.2 KB of flash) plus its class;
// this serialises through a Print&, which config_store.cpp's two sinks do as well, so all three
// share one instantiation. Measured on cyd-3248S035R: about +0.8 KB of flash for this path, against
// +4.5 KB with AsyncJsonResponse.
void sendJsonStreamed(AsyncWebServerRequest *request, JsonDocument &doc) {
  if (doc.overflowed()) {
    request->send(503, "application/json", "{\"error\":\"out of memory building the response, retry\"}");
    return;
  }
  std::shared_ptr<JsonDocument> held = std::make_shared<JsonDocument>(std::move(doc));
  request->send(request->beginChunkedResponse("application/json", [held](uint8_t *buf, size_t max_len, size_t index) -> size_t {
    ChunkPrint dest(buf, index, max_len);
    serializeJson(*held, static_cast<Print &>(dest));
    return dest.written();  // 0 once `index` has reached the end of the document = last chunk
  }));
}

void sendError(AsyncWebServerRequest *request, int code, const std::string &message, const std::string &path = "") {
  JsonDocument doc;
  doc["error"] = message;
  if (!path.empty()) {
    doc["path"] = path;
  }
  sendJson(request, code, doc);
}

// ---------------------------------------------------------------------------
// Authentication and cross-origin defence (DESIGN.md SS12; review F01/F05)
// ---------------------------------------------------------------------------

// THE single place a protected handler asks "may this request change something?". Every
// state-changing route calls requirePin() first and returns immediately if it answers false;
// there are deliberately no ad-hoc PIN comparisons anywhere else in this file, so the policy
// (which statuses, which bodies, the lockout) only ever has to be right once.
//
// The PIN travels in the custom header `X-Pin`, not a cookie and not a query parameter. That is
// what makes a blind cross-site POST harmless: a form or <img> from a malicious page can reach
// the device's LAN address, but the browser will not attach a custom header to a cross-origin
// request without a CORS preflight, and this server answers no preflight and sends no
// Access-Control-Allow-* header. A query parameter would land in browser history and server logs;
// a cookie would be sent automatically and re-open exactly the hole this closes.
constexpr const char *kPinHeader = "X-Pin";

// The status and body a rejected request gets. Kept as a value because the OTA upload handler
// decides at the first chunk (index == 0) but can only answer from its final handler.
struct ApiFailure {
  int status = 401;
  std::string message = "pin required";
  uint32_t retry_s = 0;  // 429 only
};

bool checkPin(AsyncWebServerRequest *request, ApiFailure &fail) {
  const AsyncWebHeader *h = request->getHeader(kPinHeader);
  auth::Check c = auth::check(h ? h->value().c_str() : nullptr);
  switch (c.result) {
    case auth::Result::Ok:
      return true;
    case auth::Result::Missing:
      fail = {401, "pin required", 0};
      return false;
    case auth::Result::Wrong:
      fail = {401, "wrong pin", 0};
      return false;
    case auth::Result::Locked:
    default:
      fail = {429, "too many attempts", c.retry_s};
      return false;
  }
}

void sendFailure(AsyncWebServerRequest *request, const ApiFailure &fail) {
  // Formatted on the stack, not through a JsonDocument + String: a 401/429 must still go out
  // when the heap is momentarily exhausted (the device suite saw a 401 turn into a 503 "out of
  // memory building the response" while the poller was mid-fetch). The message is one of this
  // file's own literals, never user input, so no escaping is needed.
  char body[96];
  if (fail.status == 429) {
    snprintf(body, sizeof body, "{\"error\":\"%s\",\"retry_s\":%u}", fail.message.c_str(), (unsigned)fail.retry_s);
  } else {
    snprintf(body, sizeof body, "{\"error\":\"%s\"}", fail.message.c_str());
  }
  request->send(fail.status, "application/json", body);
}

// What every protected handler calls as its first statement: answers the request itself and
// returns false when the caller may not proceed.
bool requirePin(AsyncWebServerRequest *request) {
  ApiFailure fail;
  if (checkPin(request, fail)) return true;
  sendFailure(request, fail);
  return false;
}

// The device name, lower-cased. Kept here rather than read from getActiveConfig() on every
// request: hostAllowed() runs before every handler, and copying the whole Config (eight stops of
// std::strings) per request on a 75 KB heap is real churn for one field. Written only by
// setHostName() - from startWebServer() and the PUT /api/config handler, both on the async web
// server's own task, so no lock is needed.
std::string g_host_name;

void setHostName(const std::string &name) {
  g_host_name = name;
  for (char &c : g_host_name) c = (char)tolower((unsigned char)c);
}

// DNS rebinding defence (review F05). A page on the public internet can make the browser resolve
// its own hostname to 192.168.1.x and then talk to this device with the *attacker's* origin -
// which defeats same-origin policy entirely, because as far as the browser is concerned the
// device is the attacker's site. The one thing the attacker cannot forge is the Host header: it
// carries their domain, not ours. So every request must name the device by one of the ways the
// owner can legitimately reach it, and anything else gets 421 (Misdirected Request) before a
// handler runs.
bool hostAllowed(const AsyncWebServerRequest *request) {
  std::string host = request->host().c_str();
  if (host.empty()) return false;  // HTTP/1.1 requires a Host header; a client without one is not the web UI
  // Strip an optional ":port" (IPv6 literals are not a case this device can be reached by).
  size_t colon = host.rfind(':');
  if (colon != std::string::npos) host.resize(colon);
  for (char &c : host) c = (char)tolower((unsigned char)c);
  if (host.empty()) return false;

  if (host == "localhost" || host == "192.168.4.1") return true;  // ssh tunnel / setup AP
  if (host == std::string(WiFi.localIP().toString().c_str())) return true;

  if (g_host_name.empty()) return false;
  return host == g_host_name || host == g_host_name + ".local";
}

// Reboots shortly after the current request's response has had a chance to
// go out - calling ESP.restart() directly inside the handler risks cutting
// the HTTP response off mid-flight.
void scheduleRestart() {
  xTaskCreate(
    [](void *) {
      vTaskDelay(pdMS_TO_TICKS(300));
      ESP.restart();
    },
    "restart", 2048, nullptr, 1, nullptr
  );
}

// Admission floor for the heap-heavy read handlers (/api/state copies the whole Snapshot plus
// weather and bike views into a JsonDocument; /api/config serializes the whole config): refuse with
// a fixed-literal 503 (needs almost no heap) when memory is clearly too low to build the response.
// Until 2026-09-16 this was the only defence against the uncatchable OOM-while-throwing reboot
// (device suite, 2026-09-15: bad_alloc in getBikes() <- handleGetState under load, with this SDK's
// zero-byte emergency exception pool). Now that cxx_exception_pool.cpp gives libstdc++ a pool the
// throw is catchable and guarded() answers 503 either way, so the gate is about cost, not safety: a
// build that is going to fail burns CPU and heap the poller wants, and the client retries a 503 just
// the same. It is deliberately NOT set high enough to "guarantee" a build under a concurrent
// allocation on the other core - an entry check cannot, since the poller shares this heap and can
// drop it mid-build - because a high floor just makes /api/state 503 for a long time after the heap
// fragments (largest block ~12 KB), while the build itself needs only 1 KB ArduinoJson pools and,
// since the zero-copy response (sendJsonStreamed), no body-sized contiguous block at all. The small
// handlers (debug/ui, tap, oom) are deliberately not gated: they cost little and the test/UI use
// them to observe the device precisely while it is under pressure. Normal use sits near 74 KB and
// never trips this.
constexpr size_t kMinHeavyResponseHeap = 24 * 1024;
constexpr size_t kMinHeavyResponseBlock = 8 * 1024;
bool refuseIfLowHeap(AsyncWebServerRequest *request) {
  if (ESP.getFreeHeap() >= kMinHeavyResponseHeap &&
      heap_caps_get_largest_free_block(MALLOC_CAP_8BIT) >= kMinHeavyResponseBlock) {
    return false;
  }
  request->send(503, "application/json", "{\"error\":\"low memory, retry\"}");
  return true;
}

void handleGetState(AsyncWebServerRequest *request) {
  if (refuseIfLowHeap(request)) return;
  JsonDocument doc;
  doc["time"] = (int64_t)time(nullptr);
  doc["uptime"] = (uint32_t)(millis() / 1000);
  doc["heap"] = ESP.getFreeHeap();

  Config cfg = getActiveConfig();

  JsonObject wifi = doc["wifi"].to<JsonObject>();
  wifi["ssid"] = WiFi.SSID();
  wifi["rssi"] = WiFi.RSSI();
  wifi["ip"] = WiFi.localIP().toString();
  wifi["mdns"] = cfg.device.name + ".local";

  SdStatus sd = getSdStatus();
  JsonObject sdj = doc["sd"].to<JsonObject>();
  sdj["mounted"] = sd.mounted;
  sdj["free_mb"] = (double)sd.free_bytes / (1024.0 * 1024.0);
  sdj["log_bytes"] = logBytes();
  // LittleFS (config + proxied bodies) occupancy, so a full filesystem is visible before saves fail.
  JsonObject fsj = doc["fs"].to<JsonObject>();
  fsj["used_kb"] = (uint32_t)(LittleFS.usedBytes() / 1024);
  fsj["total_kb"] = (uint32_t)(LittleFS.totalBytes() / 1024);
  sdj["dropped_rows"] = sd.dropped_rows;  // F26: rows that did not land on the card since boot
  sdj["write_ok"] = sd.last_write_ok;
  sdj["error"] = sd.error;

  PollStatus poll = getPollStatus();
  JsonObject last_poll = doc["last_poll"].to<JsonObject>();
  last_poll["ok"] = poll.ok;
  // -1 (never polled yet) vs. a real, non-negative age in seconds.
  last_poll["age_s"] = poll.has_polled ? (int32_t)((uint32_t)time(nullptr) - poll.last_poll_epoch) : (int32_t)-1;
  last_poll["error"] = poll.last_error;
  // DESIGN.md SS12.1: seconds since a cycle last COMPLETED, whatever its outcome - which is what
  // the liveness net watches, and is NOT age_s (that one only moves on a poll that reported).
  // -1 before the first cycle of this boot.
  {
    PollerLiveness lv = getPollerLiveness();
    last_poll["since_s"] = (lv.armed && !lv.before_first_cycle) ? (int32_t)(lv.since_ms / 1000U) : (int32_t)-1;
  }

  // DESIGN.md SS12.1: why the previous boot ended. `esp` is esp_reset_reason() - 1 ESP_RST_POWERON,
  // 2 ESP_RST_EXT, 3 ESP_RST_SW (what ESP.restart() produces), 4 ESP_RST_PANIC, 5/6 the interrupt
  // and task watchdogs, 9 ESP_RST_BROWNOUT - which is what distinguishes a panic from a clean
  // restart. `reason` is set only when THIS firmware restarted itself on purpose, and is ""
  // otherwise. `detail` is formatted here rather than stored, so the strings cost flash once.
  {
    JsonObject lr = doc["last_restart"].to<JsonObject>();
    lr["esp"] = (int)esp_reset_reason();
    RestartNote note = getRestartNote();
    char detail[96];
    detail[0] = '\0';
    const char *reason = "";
    if (note.reason == SelfHeal::PollStall) {
      reason = "poll_stall";
      snprintf(detail, sizeof(detail), "no poll cycle completed for %u s (interval %u s)", (unsigned)note.a, (unsigned)note.b);
    } else if (note.reason == SelfHeal::HeapWedge) {
      reason = "heap_wedge";
      snprintf(detail, sizeof(detail), "%u failed polls, largest free block %u B", (unsigned)note.a, (unsigned)note.b);
    }
    lr["reason"] = reason;
    lr["detail"] = detail;
    lr["uptime_s"] = note.uptime_s;
  }

  doc["firmware_version"] = FIRMWARE_VERSION;
  // The board this image was built for (DESIGN.md SS7). Also what POST /api/ota refuses a
  // mismatching upload against, so the web UI can name it in the error it shows.
  doc["board"] = BOARD_NAME;
  // SS7: so the web UI can say "this needs the PIN" before it makes the user fill in a form, and
  // so a future build could report false if the owner ever turns the PIN off.
  doc["auth"]["pin_required"] = true;
  // SS6 safe-save: true when the last boot had to fall back to /config.prev.json because
  // /config.json was missing or unreadable. The UI surfaces it; nothing else changes.
  doc["config_recovered"] = configRecovered();
#ifdef TRANSIT_HTTPS
  {  // DESIGN.md SS2.1: which transport the poller is actually getting, so the UI can say so.
    const TransportStats ts = transportStats();
    JsonObject tr = doc["transport"].to<JsonObject>();
    tr["policy"] = transportName(transportPolicy());
    tr["last"] = ts.last;
    tr["https_ok"] = ts.https_ok;
    tr["https_failed"] = ts.https_failed;
    tr["cert_failed"] = ts.cert_failed;
    tr["http_by_heap"] = ts.http_by_heap;
    tr["http_by_policy"] = ts.http_by_policy;
    tr["refused_by_heap"] = ts.refused_by_heap;
    tr["last_tls_error"] = ts.last_tls_error;
    tr["last_https_ms"] = ts.last_https_ms;
    tr["heap_need"] = (uint32_t)tlsHeapNeed();
    tr["gate_free"] = (uint32_t)ts.gate_free;
    tr["gate_largest"] = (uint32_t)ts.gate_largest;
  }
#endif

  // NB: doc.as<JsonObject>(), not .to<JsonObject>() - the latter clears the
  // document, which would wipe the time/uptime/heap/wifi/sd/last_poll
  // fields set above (doc's root is already an object at this point).
#ifdef DEMO_DATA
  // Kept behind a compile flag for screen work without live SEPTA data/hardware (DESIGN.md SS3);
  // default off - see firmware/README.md.
  Snapshot snap = buildDemoSnapshot((transit::Epoch)time(nullptr));
#else
  Snapshot snap = getSnapshot();
#endif
  serializeSnapshot(snap, cfg, doc.as<JsonObject>());

  sendJsonStreamed(request, doc);
}

void handleGetConfig(AsyncWebServerRequest *request) {
  if (refuseIfLowHeap(request)) return;
  Config cfg = getActiveConfig();
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJsonStreamed(request, doc);
}

// True when the parts of the config that decide what is fetched differ (stops, weather, bike).
bool dataSettingsChanged(const Config &a, const Config &b) {
  if (a.stops.size() != b.stops.size()) return true;
  for (size_t i = 0; i < a.stops.size(); ++i) {
    const transit::StopConfig &x = a.stops[i], &y = b.stops[i];
    if (x.key != y.key || x.stop_id != y.stop_id || x.route != y.route || x.station != y.station || x.direction != y.direction ||
        x.lat != y.lat || x.lng != y.lng || x.mode != y.mode) {
      return true;
    }
  }
  if (a.weather.enabled != b.weather.enabled || a.weather.per_stop != b.weather.per_stop || a.weather.fahrenheit != b.weather.fahrenheit) return true;
  if (a.bike.enabled != b.bike.enabled || a.bike.stations.size() != b.bike.stations.size()) return true;
  for (size_t i = 0; i < a.bike.stations.size(); ++i) {
    if (a.bike.stations[i].id != b.bike.stations[i].id) return true;
  }
  if (a.alerts != b.alerts || a.device.poll_seconds != b.device.poll_seconds || a.device.tz != b.device.tz) return true;
  return false;
}

void handlePutConfigInner(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged);

void handlePutConfig(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged) {
  if (!requirePin(request)) return;
  // Runs on the AsyncTCP task with the poller possibly mid-fetch: building a Config (strings,
  // vectors) can throw bad_alloc under that pressure, and an uncaught throw is a reboot (see
  // net_poller.cpp pollOnce). A 503 lets the browser retry a moment later.
  try {
    handlePutConfigInner(request, json, onConfigChanged);
  } catch (const std::bad_alloc &) {
    request->send(503, "application/json", "{\"error\":\"out of memory, retry\"}");
  }
}

void handlePutConfigInner(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged) {
  Config cfg;
  ConfigError err;
  if (!jsonToConfig(json, cfg, err)) {
    sendError(request, 400, err.message, err.path);
    return;
  }
  if (!saveConfig(cfg)) {
    sendError(request, 500, "failed to write config to LittleFS");
    return;
  }
  bool data_changed = dataSettingsChanged(getActiveConfig(), cfg);
  setActiveConfig(cfg);
  setHostName(cfg.device.name);  // a rename changes which Host headers are accepted (review F05)
  if (onConfigChanged) {
    onConfigChanged(data_changed);
  }
  // Same streamed response as GET /api/config: the 16 KB request document is still alive here, so
  // this is the moment a second body copy hurt most (SS12.1).
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJsonStreamed(request, doc);
}

// DESIGN.md SS7: POST /api/pin, body {"pin":"new"}, authenticated with the CURRENT pin in X-Pin.
// There is deliberately no "forgot my PIN" endpoint: the recovery path is physical (the serial
// console at boot, or the device info screen), see auth.h.
void handlePostPin(AsyncWebServerRequest *request, JsonVariant &json) {
  if (!requirePin(request)) return;
  JsonVariantConst body = json;
  if (!body["pin"].is<const char *>()) {
    sendError(request, 400, "body must be {\"pin\":\"...\"}", "pin");
    return;
  }
  std::string next = std::string(body["pin"].as<const char *>());
  std::string error;
  if (!auth::setPin(next, error)) {
    sendError(request, 400, error, "pin");
    return;
  }
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
}

void handlePostReboot(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  scheduleRestart();
}

void handlePostWifiReset(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  // Enable STA, erase the ESP-IDF's persisted Wi-Fi credentials, then reboot so main.cpp's
  // wifi_portal::connectWifiOrPortal() finds nothing to reconnect with and opens the setup AP.
  WiFi.mode(WIFI_STA);
  WiFi.disconnect(true, true);
  scheduleRestart();
}

// DESIGN.md SS7/SS12: "POST /api/ota; multipart `firmware` field; reboots on success."
//
// The whole upload is one transaction with an explicit outcome (review F08). The old version
// started from g_ota_ok = true, so a POST that never delivered a byte - no file part, a client
// that vanished, an unauthorised caller - answered 200 and rebooted into whatever was in the OTA
// slot. Now nothing is "ok" until the final chunk has been seen AND Update.end(true) has
// succeeded AND the image proved it was built for this board.
//
// Admission checks happen at index == 0, before Update.begin(), because that is the last moment
// at which refusing costs nothing: after it, ~1.7 MB is already on the wire.
constexpr size_t kMinOtaFreeHeap = 60 * 1024;
// Update.write() needs a contiguous scratch buffer; free heap alone can be healthy while the
// largest block is fragmented down to a few KB, which is how a mid-flash failure used to happen
// on a device that had been up for days (firmware/README.md, "Memory and flash budget").
constexpr size_t kMinOtaLargestBlock = 16 * 1024;

// Board identity, stamped into .rodata of every build and therefore into every firmware.bin
// (review F08: there is no firmware signing, but flashing a 2.4"-capacitive image onto a 3.5"
// resistive board bricks the display until someone reaches it with a USB cable). The upload is
// searched for the RUNNING device's own marker; the trailing ';' is part of the pattern so
// "cyd-2432S028R;" cannot match inside "cyd-2432S028Rv3;". `used` keeps the compiler from
// dropping it; it is referenced below anyway, which is what keeps the linker from doing so.
const char kBoardMarker[] __attribute__((used, section(".rodata"))) = "PTD-BOARD:" BOARD_NAME ";";
constexpr size_t kBoardMarkerLen = sizeof(kBoardMarker) - 1;

struct OtaState {
  const void *owner = nullptr;  // the request whose outcome this struct describes
  bool busy = false;            // a flash-writing upload is in progress
  bool writing = false;         // Update.begin() succeeded and Update.end() has not run yet
  bool ok = false;              // F08: starts false, set only when everything has succeeded
  bool final_seen = false;
  int status = 500;
  std::string error;
  uint32_t retry_s = 0;  // set with status 429 (PIN lockout), so the final handler can repeat it
  size_t written = 0;
  size_t marker_match = 0;  // how many bytes of kBoardMarker the stream has matched so far
  bool marker_found = false;
};
OtaState g_ota;

// The OTA slot is the hard ceiling on the image: Update would fail late with "Not enough space",
// after the whole upload has been drained. Knowing the size up front lets the transfer be cut off
// as soon as it is provably too big.
size_t otaSlotSize() {
  const esp_partition_t *running = esp_ota_get_running_partition();
  return running != nullptr ? running->size : 0;
}

void otaFail(int status, const std::string &message) {
  g_ota.ok = false;
  g_ota.status = status;
  g_ota.error = message;
  if (g_ota.writing) {
    Update.abort();
    g_ota.writing = false;
  }
  g_ota.busy = false;
}

// Releases the transaction when the client goes away (review F08: without this a client that
// disconnects mid-upload leaves `busy` set forever and Update holding the partition, so every
// later OTA answers 409 until the device is rebooted).
void otaRelease(const void *owner) {
  if (g_ota.owner != owner) return;  // a newer upload already took over; leave its state alone
  if (g_ota.writing) {
    log_w("web_server: OTA client disconnected mid-image, aborting");
    Update.abort();
    g_ota.writing = false;
    g_ota.ok = false;
    g_ota.status = 400;
    g_ota.error = "upload disconnected before the image was complete";
  }
  g_ota.busy = false;
}

// Streaming search for kBoardMarker. The marker can straddle any two chunks, so the match length
// carries across calls; on a mismatch it backs off to the longest prefix of the marker that is
// still a suffix of what was matched (a hand-rolled KMP step - the fallback loop only runs on the
// rare mismatch-after-partial-match, so it costs nothing on the ~1.7 MB happy path).
void otaScanForMarker(const uint8_t *data, size_t len) {
  if (g_ota.marker_found) return;
  size_t m = g_ota.marker_match;
  for (size_t i = 0; i < len; ++i) {
    uint8_t b = data[i];
    while (m > 0 && (uint8_t)kBoardMarker[m] != b) {
      size_t k = m - 1;
      while (k > 0 && memcmp(kBoardMarker, kBoardMarker + m - k, k) != 0) --k;
      m = k;
    }
    if ((uint8_t)kBoardMarker[m] == b) ++m;
    if (m == kBoardMarkerLen) {
      g_ota.marker_found = true;
      g_ota.marker_match = 0;
      return;
    }
  }
  g_ota.marker_match = m;
}

void handleOtaUpload(AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final) {
  if (index == 0) {
    if (g_ota.busy && g_ota.owner != request) {
      // Someone else is already flashing. Do not touch their state; handlePostOta() answers 409
      // for this request because it never becomes the owner.
      return;
    }
    g_ota = OtaState{};
    g_ota.owner = request;
    g_ota.status = 500;
    // Fires on client disconnect, including the normal end of the request, so the transaction is
    // released on every path out of here.
    request->onDisconnect([request]() { otaRelease(request); });

    ApiFailure fail;
    if (!checkPin(request, fail)) {
      // Unauthorised: record the outcome, write nothing, and hang up rather than politely
      // draining 1.7 MB of an attacker's upload through a device with 75 KB of heap. The final
      // handler replays `fail` as the response if the close still lets one out.
      g_ota.ok = false;
      g_ota.status = fail.status;
      g_ota.error = fail.message;
      g_ota.retry_s = fail.retry_s;
      g_ota.busy = false;
      if (request->client() != nullptr) request->client()->close();
      return;
    }

    log_w("web_server: OTA upload starting: %s", filename.c_str());
    size_t free_heap = ESP.getFreeHeap();
    size_t largest = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
    if (free_heap < kMinOtaFreeHeap) {
      otaFail(503, "refusing OTA: free heap " + std::to_string(free_heap / 1024) + " KB is below 60 KB");
      return;
    }
    if (largest < kMinOtaLargestBlock) {
      otaFail(503, "refusing OTA: largest free block " + std::to_string(largest / 1024) + " KB is below 16 KB");
      return;
    }
    if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.busy = true;
    g_ota.writing = true;
    g_ota.ok = true;
  }

  if (g_ota.owner != request || !g_ota.writing) return;  // rejected above; ignore the bytes

  if (len > 0) {  // the final call can carry no bytes at all
    size_t slot = otaSlotSize();
    if (slot != 0 && g_ota.written + len > slot) {
      otaFail(413, "firmware image is larger than the " + std::to_string(slot) + " byte OTA slot");
      if (request->client() != nullptr) request->client()->close();
      return;
    }
    if (Update.write(data, len) != len) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.written += len;
    otaScanForMarker(data, len);
  }

  if (final) {
    g_ota.final_seen = true;
    // The board check runs BEFORE Update.end(): an image for another board is a valid ESP32 image
    // and would pass end()'s own checks, and once end() has run the partition is marked bootable.
    if (!g_ota.marker_found) {
      otaFail(400, std::string("firmware is for a different board (expected ") + BOARD_NAME + ")");
      return;
    }
    if (!Update.end(true)) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.writing = false;
    g_ota.busy = false;
  }
}

void handlePostOta(AsyncWebServerRequest *request) {
  if (g_ota.owner == request) {
    if (!g_ota.ok) {
      sendFailure(request, ApiFailure{g_ota.status, g_ota.error.empty() ? "OTA failed" : g_ota.error, g_ota.retry_s});
      return;
    }
    if (!g_ota.final_seen) {
      // Update.end() was never reached: the multipart body ended without a final chunk.
      sendError(request, 400, "upload ended before the image was complete");
      return;
    }
    JsonDocument doc;
    doc["ok"] = true;
    doc["bytes"] = g_ota.written;
    doc["board"] = BOARD_NAME;
    sendJson(request, 200, doc);
    scheduleRestart();
    return;
  }
  // Never became the owner: either no file part arrived at all, or another upload holds the flash.
  if (!request->hasParam("firmware", true, true)) {
    sendError(request, 400, "no firmware file");
    return;
  }
  sendError(request, 409, "another firmware upload is in progress");
}

// DESIGN.md SS7 setup-wizard proxies: both just queue the job to proxy_worker.cpp's own task
// (never block the async web server's task on a SEPTA round trip) and return without responding -
// the worker calls request->send() itself once it has a result.
void handleProxyStops(AsyncWebServerRequest *request) {
  if (!request->hasParam("route")) {
    sendError(request, 400, "route is required");
    return;
  }
  queueStopsProxy(request, request->getParam("route")->value().c_str());
}

void handleProxySchedule(AsyncWebServerRequest *request) {
  if (!request->hasParam("stop_id")) {
    sendError(request, 400, "stop_id is required");
    return;
  }
  queueScheduleProxy(request, request->getParam("stop_id")->value().c_str());
}

// DESIGN.md SS12.1: the deterministic on-device proof of the C++ emergency exception pool
// (cxx_exception_pool.cpp). Takes the heap away in shrinking blocks until even a 16-byte allocation
// fails, then forces a std::bad_alloc: with no pool, __cxa_allocate_exception cannot get the ~100
// bytes for the exception object and calls std::terminate - a reboot - before any catch block runs;
// with the pool it lands in the catch below. Every block is freed before the response is built, and
// the body is snprintf'd into a stack buffer so answering needs no heap of its own. "largest" is the
// largest free block at the moment of the throw: under ~100 bytes proves the exception object came
// from the pool and not from a hole another task opened meanwhile. PIN-gated because it starves
// every other task for the sub-millisecond it holds the blocks (the poller and the display loop
// catch their own bad_alloc and carry on; lwIP tolerates a NULL pbuf; LVGL draws from its own pool).
void handleDebugOom(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  constexpr size_t kMaxBlocks = 200;
  static const size_t kBlockSizes[] = {1024, 256, 64, 16};
  void *blocks[kMaxBlocks];
  size_t n = 0;
  const uint32_t free_before = ESP.getFreeHeap();
  for (size_t size : kBlockSizes) {
    while (n < kMaxBlocks) {
      void *p = heap_caps_malloc(size, MALLOC_CAP_8BIT);
      if (!p) break;
      blocks[n++] = p;
    }
  }
  const size_t largest = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
  bool caught = false;
  char *volatile probe = nullptr;  // volatile: the compiler may otherwise elide an unused new/delete pair
  try {
    probe = new char[4096];
    delete[] probe;
  } catch (const std::bad_alloc &) {
    caught = true;
  }
  for (size_t i = 0; i < n; ++i) heap_caps_free(blocks[i]);
  char body[128];
  snprintf(body, sizeof body, "{\"caught\":%s,\"blocks\":%u,\"largest\":%u,\"free_before\":%u,\"free_after\":%u}",
           caught ? "true" : "false", (unsigned)n, (unsigned)largest, (unsigned)free_before, (unsigned)ESP.getFreeHeap());
  request->send(200, "application/json", body);
}

// Static list embedded in firmware (transit_core/rail_stations.h) - no network needed, so this
// runs directly on the web server's own task.
void handleRailStations(AsyncWebServerRequest *request) {
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (size_t i = 0; i < transit::kRailStationCount; ++i) {
    arr.add(transit::kRailStationNames[i]);
  }
  sendJson(request, 200, doc);
}

// DESIGN.md SS9.3: queued to proxy_worker.cpp's task since it streams one or more monthly CSV
// files off SD (never instant, and never something to do on the async server's own task).
void handleGetStats(AsyncWebServerRequest *request) {
  if (!request->hasParam("stop")) {
    sendError(request, 400, "stop is required");
    return;
  }
  std::string stop_key = request->getParam("stop")->value().c_str();
  int days = request->hasParam("days") ? atoi(request->getParam("days")->value().c_str()) : 30;
  queueStatsRequest(request, stop_key, days);
}

// DESIGN.md SS7: "[ { "file": "2026-09.csv", "bytes": 123456 } ]". Fast (a directory listing of
// at most a handful of monthly files), so this runs directly on the web server's own task.
void handleLogIndex(AsyncWebServerRequest *request) {
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (const LogFileInfo &f : listLogFiles()) {
    JsonObject o = arr.add<JsonObject>();
    o["file"] = f.name;
    o["bytes"] = f.bytes;
  }
  sendJson(request, 200, doc);
}

// GET /api/log/<file>.csv - only "YYYY-MM.csv" is accepted (guards against path traversal /
// reading anything else off the card, DESIGN.md SS12's "same posture as a printer" notwithstanding
// - there's no reason this endpoint should ever open a file other than one of its own logs).
// AsyncWebServer streams the returned File incrementally itself; this handler just opens it.
bool isLogFilename(const std::string &name) {
  // "YYYY-MM.csv": 4 digits, '-', 2 digits, ".csv" = 11 characters.
  if (name.size() != 11 || name.compare(7, 4, ".csv") != 0) return false;
  for (size_t i = 0; i < 7; ++i) {
    if (i == 4) {
      if (name[i] != '-') return false;
    } else if (!isdigit(static_cast<unsigned char>(name[i]))) {
      return false;
    }
  }
  return true;
}

bool handleLogDownload(AsyncWebServerRequest *request) {
  std::string url = request->url().c_str();
  const std::string prefix = "/api/log/";
  if (url.rfind(prefix, 0) != 0) return false;
  std::string filename = url.substr(prefix.size());
  // PIN-protected even though it only reads (DESIGN.md SS12): the CSV is a month of the owner's
  // movements - when they leave the house and which stop they leave from - which is the most
  // personal thing this device holds. `GET /api/log/index` (file names and sizes) stays open.
  if (!requirePin(request)) return true;
  if (!isLogFilename(filename)) {
    sendError(request, 400, "not a log filename");
    return true;
  }
  // One download at a time (F26): the SD mount allows two open files and the poller's append
  // needs one of them. The export re-emits every row in schema v3 (F24/F25) through a chunked
  // response; the reader lease is released by the response's completion/disconnect callback.
  if (!acquireLogReader()) {
    sendError(request, 503, "a log download is already running, try again");
    return true;
  }
  auto exp = std::make_shared<LogExport>(filename);
  if (!exp->ok()) {
    releaseLogReader();
    sendError(request, 404, "no log for that month");
    return true;
  }
  AsyncWebServerResponse *response = request->beginChunkedResponse(
      "text/csv", [exp](uint8_t *buf, size_t maxLen, size_t /*index*/) -> size_t {
        // Runs on the AsyncTCP task, outside guarded(); LogExport::fill() catches its own
        // bad_alloc, but wrap here too so no filler allocation can ever reach std::terminate.
        try {
          return exp->fill(buf, maxLen);
        } catch (const std::bad_alloc &) {
          return (size_t)0;  // ends the chunked response
        }
      });
  response->addHeader("Content-Disposition", (String("attachment; filename=\"") + filename.c_str() + "\"").c_str());
  request->onDisconnect([]() { releaseLogReader(); });
  request->send(response);
  return true;
}

#ifdef TRANSIT_HAVE_WEB_ASSETS
// DESIGN.md SS7/SS10: gzip, right content type, ETag = firmware build id (WEB_ASSETS_ETAG - a
// hash of the source assets, which is the closest stable per-build id we have without wiring a
// separate firmware build-id scheme), If-None-Match -> 304, Cache-Control max-age=3600 for the
// static assets and no-cache for "/" (its content never changes without a firmware update, but
// browsers should still re-validate it on every navigation so a stale service worker / bookmark
// doesn't hide an update the way max-age=3600 would for up to an hour).
void handleWebAsset(AsyncWebServerRequest *request, const transit_web::WebAsset &asset) {
  bool is_index = std::strcmp(asset.path, "/") == 0;

  if (request->hasHeader("If-None-Match")) {
    const AsyncWebHeader *inm = request->getHeader("If-None-Match");
    if (inm && inm->value() == transit_web::WEB_ASSETS_ETAG) {
      AsyncWebServerResponse *response = request->beginResponse(304);
      response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
      request->send(response);
      return;
    }
  }

  AsyncWebServerResponse *response = request->beginResponse(200, asset.content_type, asset.data, asset.len);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
  response->addHeader("Cache-Control", is_index ? "no-cache" : "max-age=3600");
  if (is_index) {
    // Review F05, on the document that carries the app: a hostile page that frames this UI can
    // read nothing across origins, but it can bait clicks onto controls the owner cannot see.
    // Both headers say the same thing to old and new browsers. No script-src directive on
    // purpose - the Stops page loads Leaflet from a CDN (DESIGN.md SS10) and a CSP that forbids it
    // would break the map silently; the frame directives cost nothing and break nothing.
    response->addHeader("X-Frame-Options", "DENY");
    response->addHeader("Content-Security-Policy", "frame-ancestors 'none'");
    // The UI is served gzipped from PROGMEM with fixed content types; nosniff stops a browser
    // deciding for itself that one of them is something executable.
    response->addHeader("X-Content-Type-Options", "nosniff");
  }
  request->send(response);
}

void registerWebAssets() {
  for (size_t i = 0; i < transit_web::WEB_ASSETS_COUNT; ++i) {
    const transit_web::WebAsset &asset = transit_web::WEB_ASSETS[i];
    g_server.on(asset.path, HTTP_GET, [asset](AsyncWebServerRequest *request) { handleWebAsset(request, asset); });
  }
}
#endif  // TRANSIT_HAVE_WEB_ASSETS

}  // namespace

// Every handler runs on the AsyncTCP task and copies a Config (strings, vectors) or builds a
// JsonDocument; with -fexceptions on, a bad_alloc there that nothing catches is std::terminate and
// a reboot. Under the 2026-09-15 device suite's request storms that happened while the poller held
// the heap. Wrapped, the request gets a 503 and the browser retries on its next tick.
ArRequestHandlerFunction guarded(ArRequestHandlerFunction fn) {
  return [fn](AsyncWebServerRequest *request) {
    try {
      fn(request);
    } catch (const std::bad_alloc &) {
      request->send(503, "application/json", "{\"error\":\"out of memory, retry\"}");
    }
  };
}

void startWebServer(std::function<void(bool)> onConfigChanged) {
  setHostName(getActiveConfig().device.name);

  // Runs before any handler, for every route including the static assets and the 404 (review
  // F05). Registered first so nothing can be reached without passing it.
  g_server.addMiddleware([](AsyncWebServerRequest *request, ArMiddlewareNext next) {
    // First thing on the request path, ahead of even the host check, because the host check itself
    // builds a std::string and can throw. DESIGN.md SS12.1: the AsyncTCP service task is created by
    // the library, so this is the only place we get to run code ON that task early enough to pay its
    // one-time __cxa_eh_globals allocation while the heap is healthy. Without it the task's FIRST
    // throw - which on this task is a bad_alloc under exactly the pressure guarded() exists for -
    // does a plain malloc inside __cxa_throw and terminates when it fails. Costs one
    // pthread_getspecific per request once warm; the real work happens on request number one.
    transit_app::warmExceptionGlobals("async_tcp");
    if (!hostAllowed(request)) {
      sendError(request, 421, "this device is not reachable under that host name");
      return;
    }
    next();
  });

  g_server.on("/api/state", HTTP_GET, guarded(handleGetState));
  g_server.on("/api/config", HTTP_GET, guarded(handleGetConfig));
  g_server.on("/api/config", HTTP_PUT, [onConfigChanged](AsyncWebServerRequest *request, JsonVariant &json) { handlePutConfig(request, json, onConfigChanged); });
  g_server.on("/api/pin", HTTP_POST, [](AsyncWebServerRequest *request, JsonVariant &json) {
    try {
      handlePostPin(request, json);
    } catch (const std::bad_alloc &) {
      request->send(503, "application/json", "{\"error\":\"out of memory, retry\"}");
    }
  });
  g_server.on("/api/reboot", HTTP_POST, handlePostReboot);
  // Test hooks (DESIGN.md SS7): what the screen is doing, and a simulated touch.
  g_server.on("/api/debug/ui", HTTP_GET, guarded([](AsyncWebServerRequest *request) {
    ui::UiDebug d = ui::debugSnapshot();
    JsonDocument doc;
    doc["page"] = d.page;
    doc["dimmed"] = d.dimmed;
    doc["brightness"] = d.brightness;
    doc["due_active"] = d.due_active;
    doc["chimes"] = d.chimes;
    doc["active_profile"] = d.active_profile;
    JsonArray shown = doc["shown_stops"].to<JsonArray>();
    for (const std::string &k : d.shown_stops) shown.add(k);
    JsonArray hidden = doc["hidden_panels"].to<JsonArray>();
    for (const std::string &k : d.hidden_panels) hidden.add(k);
    doc["ticker"] = d.ticker;
    doc["rows"] = d.rows;
    doc["header_weather"] = d.header_weather;
    // LVGL's static pool (lv_conf.h LV_MEM_SIZE), not the ESP heap. lv_total is what TLSF reports
    // as usable; lv_max_used is the high-water since boot, the number that says whether a page
    // cycle ever came close to the ceiling. lv_page_cost is what each page's last build took -
    // main, night, stats, device - and lv_page_refusals counts the builds the pool would not take
    // (the device stayed where it was instead; DESIGN.md SS8).
    doc["lv_used"] = d.lv_used;
    doc["lv_free"] = d.lv_free;
    doc["lv_max_used"] = d.lv_max_used;
    doc["lv_total"] = d.lv_total;
    doc["lv_frag_pct"] = d.lv_frag_pct;
    doc["lv_page_refusals"] = d.page_refusals;
    doc["lv_tight"] = d.pool_tight;  // the page that is up left under ~3 KB: it works, but only just
    JsonObject costs = doc["lv_page_cost"].to<JsonObject>();
    costs["main"] = d.page_cost[0];
    costs["night"] = d.page_cost[1];
    costs["stats"] = d.page_cost[2];
    costs["device"] = d.page_cost[3];
    doc["hor_res"] = d.hor_res;
    doc["ver_res"] = d.ver_res;
    doc["heap"] = ESP.getFreeHeap();
    doc["largest_block"] = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
    sendJson(request, 200, doc);
  }));
  g_server.on("/api/debug/tap", HTTP_POST, [](AsyncWebServerRequest *request) {
    if (!requirePin(request)) return;  // it changes what the screen shows, so it is state-changing
    ui::requestTap();
    request->send(200, "application/json", "{\"ok\":true}");
  });
  // POST /api/debug/page?page=main|night|stats|device (or the same word as the whole body): drive
  // the page cycle from the LAN without a finger on the panel. It exists because the LVGL pool is
  // the one thing the native simulator cannot reproduce - firmware/sim builds with a 512 KB
  // LV_MEM_SIZE for 64-bit pointers - so the peak a page transition reaches has to be measured on
  // the hardware, and that needs thirty cycles, not thirty taps. ui::requestPage() only sets a
  // flag the LVGL task reads in tick(); nothing here touches an lv_obj from the web server task.
  g_server.on("/api/debug/page", HTTP_POST, [](AsyncWebServerRequest *request) {
    if (!requirePin(request)) return;  // it changes what the screen shows, like /api/debug/tap
    std::string page;
    if (request->hasParam("page")) {
      page = request->getParam("page")->value().c_str();       // ?page=stats
    } else if (request->hasParam("page", true)) {
      page = request->getParam("page", true)->value().c_str();  // page=stats as a form field
    } else if (request->_tempObject != nullptr) {
      page = (const char *)request->_tempObject;                // a raw body, from the handler below
    }
    if (!ui::requestPage(page)) {
      sendError(request, 400, "page must be main, night, stats or device", "page");
      return;
    }
    request->send(200, "application/json", "{\"ok\":true}");
  }, nullptr, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) {
    // A raw body ("stats"), which is what curl -d sends. It is only PARSED here - the PIN check
    // lives in the handler above, which runs after this, and applying the page from an unchecked
    // body would be an auth bypass. Short by construction, so one chunk is the only case worth
    // handling; _tempObject is free()d with the request by ESPAsyncWebServer.
    if (index != 0 || len != total || len == 0 || len > 16 || request->_tempObject != nullptr) return;
    char *buf = (char *)malloc(len + 1);
    if (buf == nullptr) return;
    size_t n = 0;
    for (size_t i = 0; i < len; i++) {
      char c = (char)data[i];
      if (c == '\n' || c == '\r' || c == ' ') continue;
      buf[n++] = c;
    }
    buf[n] = '\0';
    request->_tempObject = buf;
  });
  g_server.on("/api/debug/oom", HTTP_POST, handleDebugOom);  // SS12.1 exception-pool proof; PIN-gated
  g_server.on("/api/wifi/reset", HTTP_POST, handlePostWifiReset);

  g_server.on("/api/proxy/stops", HTTP_GET, handleProxyStops);
  g_server.on("/api/proxy/schedule", HTTP_GET, handleProxySchedule);
  g_server.on("/api/rail/stations", HTTP_GET, handleRailStations);
  startProxyWorker();

  // Registered before /api/stats: ESPAsyncWebServer matches handler URIs by prefix, so the
  // longer path has to come first or handleGetStats answers it with "stop is required".
  g_server.on("/api/stats/overview", HTTP_GET, [](AsyncWebServerRequest *request) {
    int days = request->hasParam("days") ? atoi(request->getParam("days")->value().c_str()) : 7;
    queueOverviewRequest(request, days);
  });
  g_server.on("/api/stats", HTTP_GET, handleGetStats);
  g_server.on("/api/log/index", HTTP_GET, handleLogIndex);
  // "/api/log/<file>.csv" - matched with a regex-free prefix check in onNotFound below instead of
  // a wildcard pattern, to keep the matcher simple.

  g_server.on("/api/ota", HTTP_POST, handlePostOta, handleOtaUpload);

#ifdef TRANSIT_HAVE_WEB_ASSETS
  registerWebAssets();
#else
  g_server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/plain", "web UI not built into this firmware (web/build.mjs never ran) - try /api/state");
  });
#endif

  g_server.onNotFound([](AsyncWebServerRequest *request) {
    if (request->url().startsWith("/api/log/") && handleLogDownload(request)) {
      return;
    }
    request->send(404, "application/json", "{\"error\":\"not found\"}");
  });

  g_server.begin();
  log_i("web_server: listening on port 80");
}

bool otaBusy() { return g_ota.busy; }

}  // namespace transit_app
