#include "web_server.h"

#include <Arduino.h>
#include <ESPAsyncWebServer.h>
#include <Update.h>
#include <WiFi.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <cctype>
#include <cstring>
#include <ctime>

#include "config_store.h"
#include "demo_data.h"
#include "net_poller.h"
#include "weather_service.h"
#include "proxy_worker.h"
#include "sd_logger.h"
#include "transit_core/rail_stations.h"

// Generated by web/build.mjs from web/ (DESIGN.md SS10): WEB_ASSETS[] (path, content_type,
// gzipped PROGMEM bytes, length), WEB_ASSETS_COUNT, and WEB_ASSETS_ETAG (see registerWebAssets()
// below). Guarded so this file still compiles in the (now purely historical) case the generated
// header is missing.
#if __has_include("generated/web_assets.h")
#include "generated/web_assets.h"
#define TRANSIT_HAVE_WEB_ASSETS 1
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "unknown"
#endif

using transit::Alert;
using transit::Arrival;
using transit::Snapshot;
using transit::Status;
using transit::StopSnapshot;

namespace transit_app {

namespace {

AsyncWebServer g_server(80);

const char *statusToString(Status s) {
  switch (s) {
    case Status::Live:
      return "live";
    case Status::Scheduled:
      return "scheduled";
    case Status::Skipped:
      return "skipped";
    case Status::Unknown:
    default:
      return "unknown";
  }
}

// DESIGN.md SS7's Arrival object shape.
void serializeArrival(const Arrival &a, JsonObject o, transit::Epoch now) {
  o["trip"] = a.trip;
  o["vehicle"] = a.vehicle;
  o["destination"] = a.destination;
  o["predicted"] = a.predicted;
  o["scheduled"] = a.scheduled;
  o["eta_s"] = a.effective() > 0 ? (a.effective() - now) : 0;
  o["late_min"] = a.late_min;
  o["late_known"] = a.late_known;
  o["status"] = statusToString(a.status);
  o["seats"] = a.seats;
}

void serializeSnapshot(const Snapshot &snap, JsonObject out) {
  transit::Epoch now = (transit::Epoch)time(nullptr);
  // The web UI titles each panel from these config fields, so echo them next to the live data.
  Config cfg = getActiveConfig();
  JsonArray stops = out["stops"].to<JsonArray>();
  for (const StopSnapshot &s : snap.stops) {
    JsonObject so = stops.add<JsonObject>();
    so["key"] = s.key;
    for (const transit::StopConfig &sc : cfg.stops) {
      if (sc.key != s.key) continue;
      so["mode"] = sc.mode == transit::Mode::Rail ? "rail" : sc.mode == transit::Mode::Subway ? "subway" : sc.mode == transit::Mode::Trolley ? "trolley" : "bus";
      so["route"] = sc.route;
      so["stop_id"] = sc.stop_id;
      so["station"] = sc.station;
      so["direction"] = sc.direction;
      so["headsign"] = sc.headsign;
      so["label"] = sc.label;
      so["stop_name"] = sc.stop_name;
      so["show"] = sc.show;
      break;
    }
    so["ok"] = s.ok;
    so["error"] = s.error;
    so["weather_note"] = stopWeatherNote(s.key, s.arrivals.empty() ? 0 : s.arrivals.front().effective());
    JsonArray arrivals = so["arrivals"].to<JsonArray>();
    for (const Arrival &a : s.arrivals) {
      serializeArrival(a, arrivals.add<JsonObject>(), now);
    }
  }
  // DESIGN.md SS4.8/SS7: the main location's conditions plus the hourly slots the notes use.
  WeatherView wv = getWeather();
  JsonObject weather = out["weather"].to<JsonObject>();
  weather["enabled"] = wv.enabled;
  weather["units"] = wv.fahrenheit ? "f" : "c";
  weather["age_s"] = wv.fetched_epoch > 0 ? (int64_t)now - (int64_t)wv.fetched_epoch : -1;
  if (wv.main.valid()) {
    JsonObject m = weather["main"].to<JsonObject>();
    m["temp"] = wv.main.temp;
    m["feels_like"] = wv.main.feels_like;
    m["code"] = wv.main.code;
    m["text"] = weather::codeText(wv.main.code);
    m["wind"] = wv.main.wind;
    JsonArray hours = m["hours"].to<JsonArray>();
    for (const weather::Hour &h : wv.main.hours) {
      JsonObject ho = hours.add<JsonObject>();
      ho["t"] = h.epoch;
      ho["code"] = h.code;
      ho["text"] = weather::codeText(h.code);
      ho["prob"] = h.precip_prob;
      ho["temp"] = h.temp;
    }
  }
  JsonArray alerts = out["alerts"].to<JsonArray>();
  for (const Alert &al : snap.alerts) {
    JsonObject ao = alerts.add<JsonObject>();
    ao["route"] = al.route;
    ao["text"] = al.text;
    ao["current"] = al.current;
    JsonArray detours = ao["detours"].to<JsonArray>();
    for (const std::string &d : al.detours) {
      detours.add(d);
    }
  }
}

void sendJson(AsyncWebServerRequest *request, int code, JsonDocument &doc) {
  String body;
  serializeJson(doc, body);
  request->send(code, "application/json", body);
}

void sendError(AsyncWebServerRequest *request, int code, const std::string &message, const std::string &path = "") {
  JsonDocument doc;
  doc["error"] = message;
  if (!path.empty()) {
    doc["path"] = path;
  }
  sendJson(request, code, doc);
}

// Reboots shortly after the current request's response has had a chance to
// go out - calling ESP.restart() directly inside the handler risks cutting
// the HTTP response off mid-flight.
void scheduleRestart() {
  xTaskCreate(
    [](void *) {
      vTaskDelay(pdMS_TO_TICKS(300));
      ESP.restart();
    },
    "restart", 2048, nullptr, 1, nullptr
  );
}

void handleGetState(AsyncWebServerRequest *request) {
  JsonDocument doc;
  doc["time"] = (int64_t)time(nullptr);
  doc["uptime"] = (uint32_t)(millis() / 1000);
  doc["heap"] = ESP.getFreeHeap();

  Config cfg = getActiveConfig();

  JsonObject wifi = doc["wifi"].to<JsonObject>();
  wifi["ssid"] = WiFi.SSID();
  wifi["rssi"] = WiFi.RSSI();
  wifi["ip"] = WiFi.localIP().toString();
  wifi["mdns"] = cfg.device.name + ".local";

  SdStatus sd = getSdStatus();
  JsonObject sdj = doc["sd"].to<JsonObject>();
  sdj["mounted"] = sd.mounted;
  sdj["free_mb"] = (double)sd.free_bytes / (1024.0 * 1024.0);
  sdj["log_bytes"] = logBytes();

  PollStatus poll = getPollStatus();
  JsonObject last_poll = doc["last_poll"].to<JsonObject>();
  last_poll["ok"] = poll.ok;
  // -1 (never polled yet) vs. a real, non-negative age in seconds.
  last_poll["age_s"] = poll.has_polled ? (int32_t)((uint32_t)time(nullptr) - poll.last_poll_epoch) : (int32_t)-1;
  last_poll["error"] = poll.last_error;

  doc["firmware_version"] = FIRMWARE_VERSION;

  // NB: doc.as<JsonObject>(), not .to<JsonObject>() - the latter clears the
  // document, which would wipe the time/uptime/heap/wifi/sd/last_poll
  // fields set above (doc's root is already an object at this point).
#ifdef DEMO_DATA
  // Kept behind a compile flag for screen work without live SEPTA data/hardware (DESIGN.md SS3);
  // default off - see firmware/README.md.
  Snapshot snap = buildDemoSnapshot((transit::Epoch)time(nullptr));
#else
  Snapshot snap = getSnapshot();
#endif
  serializeSnapshot(snap, doc.as<JsonObject>());

  sendJson(request, 200, doc);
}

void handleGetConfig(AsyncWebServerRequest *request) {
  Config cfg = getActiveConfig();
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJson(request, 200, doc);
}

void handlePutConfig(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void()> &onConfigChanged) {
  Config cfg;
  ConfigError err;
  if (!jsonToConfig(json, cfg, err)) {
    sendError(request, 400, err.message, err.path);
    return;
  }
  if (!saveConfig(cfg)) {
    sendError(request, 500, "failed to write config to LittleFS");
    return;
  }
  setActiveConfig(cfg);
  if (onConfigChanged) {
    onConfigChanged();
  }
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJson(request, 200, doc);
}

void handlePostReboot(AsyncWebServerRequest *request) {
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  scheduleRestart();
}

void handlePostWifiReset(AsyncWebServerRequest *request) {
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  // Enable STA, erase the ESP-IDF's persisted Wi-Fi credentials, then reboot so main.cpp's
  // wifi_portal::connectWifiOrPortal() finds nothing to reconnect with and opens the setup AP.
  WiFi.mode(WIFI_STA);
  WiFi.disconnect(true, true);
  scheduleRestart();
}

// DESIGN.md SS7/SS12: "POST /api/ota; multipart `firmware` field; reboots on success." Refuses to
// even start when free heap is below kMinOtaFreeHeap - flashing a new image needs a contiguous
// scratch buffer plus everything else already running (LVGL, Wi-Fi/TLS, the poller), and starting
// anyway just to fail partway through is worse than refusing up front. State is file-scope
// (single AsyncWebServer, one OTA at a time in practice - a LAN device, not a fleet) rather than
// per-request, since ArUploadHandlerFunction has no natural place to stash it across calls other
// than the request object itself, and this is simpler.
constexpr size_t kMinOtaFreeHeap = 60 * 1024;
bool g_ota_ok = true;
std::string g_ota_error;

void handleOtaUpload(AsyncWebServerRequest * /*request*/, const String &filename, size_t index, uint8_t *data, size_t len, bool final) {
  if (index == 0) {
    g_ota_ok = true;
    g_ota_error.clear();
    log_w("web_server: OTA upload starting: %s", filename.c_str());
    if (ESP.getFreeHeap() < kMinOtaFreeHeap) {
      g_ota_ok = false;
      g_ota_error = "refusing OTA: free heap below 60KB";
    } else if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
      g_ota_ok = false;
      g_ota_error = Update.errorString();
    }
  }
  if (!g_ota_ok) return;  // still drains the rest of the upload; just ignores the bytes

  if (Update.write(data, len) != len) {
    g_ota_ok = false;
    g_ota_error = Update.errorString();
    return;
  }
  if (final && !Update.end(true)) {
    g_ota_ok = false;
    g_ota_error = Update.errorString();
  }
}

void handlePostOta(AsyncWebServerRequest *request) {
  if (!g_ota_ok) {
    sendError(request, 500, g_ota_error.empty() ? "OTA failed" : g_ota_error);
    return;
  }
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  scheduleRestart();
}

// DESIGN.md SS7 setup-wizard proxies: both just queue the job to proxy_worker.cpp's own task
// (never block the async web server's task on a SEPTA round trip) and return without responding -
// the worker calls request->send() itself once it has a result.
void handleProxyStops(AsyncWebServerRequest *request) {
  if (!request->hasParam("route")) {
    sendError(request, 400, "route is required");
    return;
  }
  queueStopsProxy(request, request->getParam("route")->value().c_str());
}

void handleProxySchedule(AsyncWebServerRequest *request) {
  if (!request->hasParam("stop_id")) {
    sendError(request, 400, "stop_id is required");
    return;
  }
  queueScheduleProxy(request, request->getParam("stop_id")->value().c_str());
}

// Static list embedded in firmware (transit_core/rail_stations.h) - no network needed, so this
// runs directly on the web server's own task.
void handleRailStations(AsyncWebServerRequest *request) {
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (size_t i = 0; i < transit::kRailStationCount; ++i) {
    arr.add(transit::kRailStationNames[i]);
  }
  sendJson(request, 200, doc);
}

// DESIGN.md SS9.3: queued to proxy_worker.cpp's task since it streams one or more monthly CSV
// files off SD (never instant, and never something to do on the async server's own task).
void handleGetStats(AsyncWebServerRequest *request) {
  if (!request->hasParam("stop")) {
    sendError(request, 400, "stop is required");
    return;
  }
  std::string stop_key = request->getParam("stop")->value().c_str();
  int days = request->hasParam("days") ? atoi(request->getParam("days")->value().c_str()) : 30;
  queueStatsRequest(request, stop_key, days);
}

// DESIGN.md SS7: "[ { "file": "2026-09.csv", "bytes": 123456 } ]". Fast (a directory listing of
// at most a handful of monthly files), so this runs directly on the web server's own task.
void handleLogIndex(AsyncWebServerRequest *request) {
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (const LogFileInfo &f : listLogFiles()) {
    JsonObject o = arr.add<JsonObject>();
    o["file"] = f.name;
    o["bytes"] = f.bytes;
  }
  sendJson(request, 200, doc);
}

// GET /api/log/<file>.csv - only "YYYY-MM.csv" is accepted (guards against path traversal /
// reading anything else off the card, DESIGN.md SS12's "same posture as a printer" notwithstanding
// - there's no reason this endpoint should ever open a file other than one of its own logs).
// AsyncWebServer streams the returned File incrementally itself; this handler just opens it.
bool isLogFilename(const std::string &name) {
  // "YYYY-MM.csv": 4 digits, '-', 2 digits, ".csv" = 11 characters.
  if (name.size() != 11 || name.compare(7, 4, ".csv") != 0) return false;
  for (size_t i = 0; i < 7; ++i) {
    if (i == 4) {
      if (name[i] != '-') return false;
    } else if (!isdigit(static_cast<unsigned char>(name[i]))) {
      return false;
    }
  }
  return true;
}

bool handleLogDownload(AsyncWebServerRequest *request) {
  std::string url = request->url().c_str();
  const std::string prefix = "/api/log/";
  if (url.rfind(prefix, 0) != 0) return false;
  std::string filename = url.substr(prefix.size());
  if (!isLogFilename(filename)) {
    sendError(request, 400, "not a log filename");
    return true;
  }
  File f = openLogFile(filename);
  if (!f) {
    sendError(request, 404, "no log for that month");
    return true;
  }
  AsyncWebServerResponse *response = request->beginResponse(f, filename.c_str(), "text/csv", true);
  request->send(response);
  return true;
}

#ifdef TRANSIT_HAVE_WEB_ASSETS
// DESIGN.md SS7/SS10: gzip, right content type, ETag = firmware build id (WEB_ASSETS_ETAG - a
// hash of the source assets, which is the closest stable per-build id we have without wiring a
// separate firmware build-id scheme), If-None-Match -> 304, Cache-Control max-age=3600 for the
// static assets and no-cache for "/" (its content never changes without a firmware update, but
// browsers should still re-validate it on every navigation so a stale service worker / bookmark
// doesn't hide an update the way max-age=3600 would for up to an hour).
void handleWebAsset(AsyncWebServerRequest *request, const transit_web::WebAsset &asset) {
  bool is_index = std::strcmp(asset.path, "/") == 0;

  if (request->hasHeader("If-None-Match")) {
    const AsyncWebHeader *inm = request->getHeader("If-None-Match");
    if (inm && inm->value() == transit_web::WEB_ASSETS_ETAG) {
      AsyncWebServerResponse *response = request->beginResponse(304);
      response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
      request->send(response);
      return;
    }
  }

  AsyncWebServerResponse *response = request->beginResponse(200, asset.content_type, asset.data, asset.len);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
  response->addHeader("Cache-Control", is_index ? "no-cache" : "max-age=3600");
  request->send(response);
}

void registerWebAssets() {
  for (size_t i = 0; i < transit_web::WEB_ASSETS_COUNT; ++i) {
    const transit_web::WebAsset &asset = transit_web::WEB_ASSETS[i];
    g_server.on(asset.path, HTTP_GET, [asset](AsyncWebServerRequest *request) { handleWebAsset(request, asset); });
  }
}
#endif  // TRANSIT_HAVE_WEB_ASSETS

}  // namespace

void startWebServer(std::function<void()> onConfigChanged) {
  g_server.on("/api/state", HTTP_GET, handleGetState);
  g_server.on("/api/config", HTTP_GET, handleGetConfig);
  g_server.on("/api/config", HTTP_PUT, [onConfigChanged](AsyncWebServerRequest *request, JsonVariant &json) { handlePutConfig(request, json, onConfigChanged); });
  g_server.on("/api/reboot", HTTP_POST, handlePostReboot);
  g_server.on("/api/wifi/reset", HTTP_POST, handlePostWifiReset);

  g_server.on("/api/proxy/stops", HTTP_GET, handleProxyStops);
  g_server.on("/api/proxy/schedule", HTTP_GET, handleProxySchedule);
  g_server.on("/api/rail/stations", HTTP_GET, handleRailStations);
  startProxyWorker();

  g_server.on("/api/stats", HTTP_GET, handleGetStats);
  g_server.on("/api/log/index", HTTP_GET, handleLogIndex);
  // "/api/log/<file>.csv" - matched with a regex-free prefix check in onNotFound below instead of
  // a wildcard pattern, to keep the matcher simple.

  g_server.on("/api/ota", HTTP_POST, handlePostOta, handleOtaUpload);

#ifdef TRANSIT_HAVE_WEB_ASSETS
  registerWebAssets();
#else
  g_server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/plain", "web UI not built into this firmware (web/build.mjs never ran) - try /api/state");
  });
#endif

  g_server.onNotFound([](AsyncWebServerRequest *request) {
    if (request->url().startsWith("/api/log/") && handleLogDownload(request)) {
      return;
    }
    request->send(404, "application/json", "{\"error\":\"not found\"}");
  });

  g_server.begin();
  log_i("web_server: listening on port 80");
}

}  // namespace transit_app
