#include "web_server.h"

#include <Arduino.h>
#include <ESPAsyncWebServer.h>
#include <LittleFS.h>
#include <Update.h>
#include <WiFi.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <cctype>
#include <cstdio>   // snprintf() for the heap-trace rows (diag branch)
#include <cstdlib>  // strtoul() for the heap-trace query params (diag branch)
#include <cstring>
#include <ctime>
#include <array>
#include <atomic>
#include <memory>
#include <new>

#include "auth.h"
#include "admission.h"
#include "config_store.h"
#include "cpu_yield.h"  // cpuStretchMsMax() for /api/debug/ui (DESIGN.md SS12.1)
#include "cxx_exception_pool.h"
#include "demo_data.h"
#include "cycle_log.h"  // the per-cycle memory log served by /api/debug/ui?log=1
#include "wedge_policy.h"  // kOomPollsBeforeReboot for /api/debug/ui
#include "heap_trace.h"  // the poll-cycle heap ring for /api/debug/ui (diag branch)
#include "host_match.h"
#include "heap_reserve.h"
#include "json_response.h"
#include "oom_reply.h"
#include "net_poller.h"
#include "weather_service.h"
#include "ui/ui.h"
#include <esp_heap_caps.h>
#include <esp_ota_ops.h>
#include <esp_system.h>  // esp_reset_reason() for /api/state's last_restart (DESIGN.md SS12.1)
#include "bike_service.h"
#include "profiles.h"
#include "proxy_worker.h"
#ifdef TRANSIT_HTTPS
#include "http_fetch.h"  // transport stats for /api/state (DESIGN.md SS2.1)
#endif
#include "sd_logger.h"
#include "transit_core/rail_stations.h"

// Generated by web/build.mjs from web/ (DESIGN.md SS10): WEB_ASSETS[] (path, content_type,
// gzipped PROGMEM bytes, length), WEB_ASSETS_COUNT, and WEB_ASSETS_ETAG (see registerWebAssets()
// below). Guarded so this file still compiles in the (now purely historical) case the generated
// header is missing.
#if __has_include("generated/web_assets.h")
#include "generated/web_assets.h"
#define TRANSIT_HAVE_WEB_ASSETS 1
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "unknown"
#endif
#ifndef BOARD_NAME
#define BOARD_NAME "unknown"
#endif

using transit::Alert;
using transit::Arrival;
using transit::Snapshot;
using transit::Status;
using transit::StopSnapshot;

namespace transit_app {

namespace {

// ---- Admission control at accept time (admission.h, DESIGN.md SS12.1) -------------------------
//
// The fourth uncatchable-OOM instance: the library assembles a response's header list LATER, from
// inside _parseLine, on a frame with no handler of ours above it, so neither the 1 KB reserve nor
// oom_reply.h's nested try/catch can reach the allocation that crashed the device suite's section E
// burst. admission.h has the backtrace and the arithmetic. The only lever left is to refuse the
// connection before ANYTHING is built for it.
//
// HOW IN-FLIGHT REQUESTS ARE COUNTED, and why it is weak_ptrs rather than a counter. The obvious
// design - increment at accept, decrement on disconnect - has nowhere to put the decrement:
// AsyncWebServerRequest's constructor overwrites every AsyncClient callback, and the one user hook
// the library offers, request->onDisconnect(), is a SINGLE slot that three call sites in this
// firmware already own (the proxy file lease, the OTA guard and the log-download lease). Taking it
// would break them; chaining would need a per-request registry.
//
// AsyncWebServerRequest::create() hands back a shared_ptr whose control block IS the request's
// lifetime - _onDisconnect() drops the self-reference and the object destructs. A weak_ptr to it
// therefore expires exactly when the request is gone, needs no hook, collides with nothing, and
// costs no allocation to copy or test. Sweeping the array is the count.
//
// TASK SAFETY: every touch of g_in_flight_slots happens on the AsyncTCP task (the accept callback
// and HostGuardHandler::canHandle), so the array needs no lock. g_in_flight_count is the atomic
// snapshot the poller task reads for its job gate; it can be a few milliseconds stale, which for a
// gate that only has to say "is a burst happening" is fine.
std::array<std::weak_ptr<AsyncWebServerRequest>, kMaxInFlightRequests + 3> g_in_flight_slots;
std::atomic<uint32_t> g_in_flight_count{0};
std::atomic<uint32_t> g_admission_refusals{0};

// Drops expired slots and returns how many requests are alive. AsyncTCP task only. Allocates
// nothing and cannot throw: weak_ptr::expired() and reset() only touch an existing control block.
uint32_t sweepInFlight() {
  uint32_t live = 0;
  for (auto &slot : g_in_flight_slots) {
    if (slot.expired()) {
      slot.reset();
    } else {
      ++live;
    }
  }
  g_in_flight_count.store(live, std::memory_order_relaxed);
  return live;
}

// Records a newly admitted request in the first free slot. The array is larger than the cap, so
// after a successful admission there is always one; if there somehow is not, the request still
// runs - it is simply not counted, which errs toward serving rather than refusing.
void rememberInFlight(const std::shared_ptr<AsyncWebServerRequest> &r) {
  for (auto &slot : g_in_flight_slots) {
    if (slot.expired()) {
      slot = r;
      g_in_flight_count.fetch_add(1, std::memory_order_relaxed);
      return;
    }
  }
}

// AsyncWebServer with the accept path replaced. `_server` is protected in the library, so a
// subclass can re-register the AsyncServer's onClient callback; the base constructor installs the
// library's version first and this one replaces it. The body below is the library's own
// (WebServer.cpp's constructor), with the admission check in front of it and a try/catch around
// it - the library's version has neither, and a throw on this task is std::terminate.
class GatedWebServer : public AsyncWebServer {
 public:
  explicit GatedWebServer(uint16_t port) : AsyncWebServer(port) {
    _server.onClient(
      [](void *s, AsyncClient *c) {
        if (c == nullptr) return;
        try {
          const uint32_t live = sweepInFlight();
          const size_t free8 = heap_caps_get_free_size(MALLOC_CAP_8BIT);
          // The one sample the per-cycle log takes from OUTSIDE the poller task (cycle_log.h). The
          // troughs that matter are a poll mid-fetch plus a concurrent request on this task, and
          // the poller's own stage boundaries cannot see the second half of that. It is free here:
          // the number has already been read for the admission decision.
          cycleLogNoteFree8((uint32_t)free8);
          if (!admitConnection(live, free8,
                                heap_caps_get_largest_free_block(MALLOC_CAP_8BIT))) {
            // Zero allocations on this path, which is the entire point: no request, no response,
            // no header list, no send buffer. The client sees a closed connection, which the web
            // app's resilientRead() already treats as retryable (DESIGN.md SS10.2) and the device
            // suite counts against its refusal budget alongside the empty-200 shape.
            //
            // Since 0.3.2-rc1 this can no longer be reached with `live == 0`: admission.h admits
            // the only connection whatever the heap says, because refusing it locked the owner's
            // board out of /api/debug/ui and /api/reboot for five minutes on 2026-09-17 with a
            // 3,444 B largest block. A refusal here therefore always means "something else is
            // already being served".
            // abort(), not close(): AsyncClient::abort() calls tcp_abort(), which sends an RST
            // and frees the pcb immediately, so a refused connection leaves NOTHING behind -
            // no TIME_WAIT, no lwIP pcb held for two minutes out of the sixteen this build has.
            // A graceful close would FIN and park a pcb in TIME_WAIT, and a client polling a
            // refusing server every ten seconds would then exhaust them. Checked against
            // AsyncTCP's own source: abort() nulls _pcb, so the destructor's _close() is skipped
            // and the delete below is not a double free; _error_cb/_discard_cb are still null on a
            // connection this new, so nothing can delete the client out from under us either.
            g_admission_refusals.fetch_add(1, std::memory_order_relaxed);
            c->abort();
            delete c;
            return;
          }
          c->setRxTimeout(3);  // the library's own value
          std::shared_ptr<AsyncWebServerRequest> r =
            AsyncWebServerRequest::create(static_cast<AsyncWebServer *>(s), c);
          if (!r) {
            c->abort();
            delete c;
            return;
          }
          rememberInFlight(r);
        } catch (const std::bad_alloc &) {
          // create() allocates with nothrow, but the request's constructor builds Strings and
          // std::functions. The library runs this callback with no catch above it anywhere, so
          // without this a throw here is std::terminate - the same shape as everything else in
          // DESIGN.md SS12.1's list.
          g_admission_refusals.fetch_add(1, std::memory_order_relaxed);
          c->abort();
          delete c;
        }
      },
      this
    );
  }
};

GatedWebServer g_server(80);

const char *statusToString(Status s) {
  switch (s) {
    case Status::Live:
      return "live";
    case Status::Scheduled:
      return "scheduled";
    case Status::Skipped:
      return "skipped";
    case Status::Unknown:
    default:
      return "unknown";
  }
}

// DESIGN.md SS7's Arrival object shape.
void serializeArrival(const Arrival &a, JsonObject o, transit::Epoch now) {
  o["trip"] = a.trip;
  o["vehicle"] = a.vehicle;
  o["destination"] = a.destination;
  o["predicted"] = a.predicted;
  o["scheduled"] = a.scheduled;
  o["eta_s"] = a.effective() > 0 ? (a.effective() - now) : 0;
  o["late_min"] = a.late_min;
  o["late_known"] = a.late_known;
  o["status"] = statusToString(a.status);
  o["seats"] = a.seats;
  o["sched_trip"] = a.sched_trip;  // matched static-schedule trip id, "" when unmatched (DESIGN.md SS7)
}

// transit::Health as the wire token GET /api/state uses (model.h, DESIGN.md SS4.7/SS7).
const char *healthToString(transit::Health h) {
  switch (h) {
    case transit::Health::Live:
      return "live";
    case transit::Health::ScheduleOnly:
      return "schedule_only";
    case transit::Health::Stale:
      return "stale";
    case transit::Health::Unavailable:
    default:
      return "unavailable";
  }
}

// `cfg` is the caller's copy of the active config (handleGetState already holds one): the web UI
// titles each panel from its fields, so they are echoed next to the live data. Taking it by
// reference rather than copying again keeps a second Config (eight stops of std::strings) out of
// the request's peak (SS12.1).
void serializeSnapshot(const Snapshot &snap, const Config &cfg, JsonObject out) {
  transit::Epoch now = (transit::Epoch)time(nullptr);
  JsonArray stops = out["stops"].to<JsonArray>();
  for (const StopSnapshot &s : snap.stops) {
    JsonObject so = stops.add<JsonObject>();
    so["key"] = s.key;
    for (const transit::StopConfig &sc : cfg.stops) {
      if (sc.key != s.key) continue;
      so["mode"] = sc.mode == transit::Mode::Rail ? "rail" : sc.mode == transit::Mode::Subway ? "subway" : sc.mode == transit::Mode::Trolley ? "trolley" : "bus";
      so["route"] = sc.route;
      so["stop_id"] = sc.stop_id;
      so["station"] = sc.station;
      so["direction"] = sc.direction;
      so["headsign"] = sc.headsign;
      so["label"] = sc.label;
      so["stop_name"] = sc.stop_name;
      so["show"] = sc.show;
      break;
    }
    so["ok"] = s.ok;
    so["error"] = s.error;
    so["health"] = healthToString(s.health);
    so["source_ts"] = s.source_ts;  // when SEPTA produced the data; 0 = the feed carried no timestamp
    so["source_age_s"] = s.source_ts > 0 ? (int64_t)(now - s.source_ts) : (int64_t)-1;
    so["weather_note"] = stopWeatherNote(s.key, s.arrivals.empty() ? 0 : s.arrivals.front().effective());
    JsonArray arrivals = so["arrivals"].to<JsonArray>();
    for (const Arrival &a : s.arrivals) {
      serializeArrival(a, arrivals.add<JsonObject>(), now);
    }
  }
  // DESIGN.md SS4.8/SS7: the main location's conditions plus the hourly slots the notes use.
  WeatherView wv = getWeather();
  JsonObject weather = out["weather"].to<JsonObject>();
  weather["enabled"] = cfg.weather.enabled;  // the config, not the last poll: a save applies at once
  weather["units"] = wv.fahrenheit ? "f" : "c";
  weather["age_s"] = wv.age_s;  // main location's last SUCCESS, millis-based, -1 = never (F29)
  weather["stale"] = wv.stale;  // over 60 min old: the device suppresses the header icon and notes
  if (cfg.weather.enabled && wv.main.valid()) {
    JsonObject m = weather["main"].to<JsonObject>();
    m["temp"] = wv.main.temp;
    m["feels_like"] = wv.main.feels_like;
    m["code"] = wv.main.code;
    m["text"] = weather::codeText(wv.main.code);
    m["wind"] = wv.main.wind;
    JsonArray hours = m["hours"].to<JsonArray>();
    for (const weather::Hour &h : wv.main.hours) {
      JsonObject ho = hours.add<JsonObject>();
      ho["t"] = h.epoch;
      ho["code"] = h.code;
      ho["text"] = weather::codeText(h.code);
      ho["prob"] = h.precip_prob;
      ho["temp"] = h.temp;
    }
  }
  int prof = activeProfileIndex(cfg, (time_t)now);
  out["active_profile"] = prof >= 0 ? cfg.profiles[(size_t)prof].name : "";
  BikeView bv = getBikes();
  JsonObject bike = out["bike"].to<JsonObject>();
  bike["enabled"] = cfg.bike.enabled;
  bike["age_s"] = bv.fetched_epoch > 0 ? (int64_t)now - (int64_t)bv.fetched_epoch : -1;
  JsonArray bstations = bike["stations"].to<JsonArray>();
  // In config order, with counts from the last fetch when that station was part of it; a station
  // added a moment ago shows -1 until the poller catches up rather than being missing.
  for (const BikeStation &cs : cfg.bike.stations) {
    if (!cfg.bike.enabled) break;
    indego::Station st;
    st.id = cs.id;
    st.name = cs.name;
    for (const indego::Station &f : bv.stations) {
      if (f.id == cs.id) {
        st = f;
        if (st.name.empty()) st.name = cs.name;
        break;
      }
    }
    JsonObject so = bstations.add<JsonObject>();
    so["id"] = st.id;
    so["name"] = st.name;
    so["bikes"] = st.bikes;
    so["ebikes"] = st.ebikes;
    so["classic"] = st.classic;
    so["docks"] = st.docks;
    so["total_docks"] = st.total_docks;
    so["active"] = st.active;
  }
  JsonArray alerts = out["alerts"].to<JsonArray>();
  for (const Alert &al : snap.alerts) {
    if (!cfg.alerts) break;  // the config, not the last poll
    JsonObject ao = alerts.add<JsonObject>();
    ao["route"] = al.route;
    ao["text"] = al.text;
    ao["current"] = al.current;
    JsonArray detours = ao["detours"].to<JsonArray>();
    for (const std::string &d : al.detours) {
      detours.add(d);
    }
  }
}

void sendJson(AsyncWebServerRequest *request, int code, JsonDocument &doc) {
  // Under memory pressure (several concurrent requests on a ~65 KB heap) ArduinoJson silently
  // truncates the document and String silently stays empty; both used to go out as an empty
  // HTTP 200. A 503 lets the web UI keep the last good state and try again on its next poll.
  String body;
  bool ok = !doc.overflowed() && serializeJson(doc, body) > 0 && body.length() > 0;
  if (!ok) {
    // sendUnderPressure(), not send(): this reply is on an out-of-memory path and the response
    // object it needs is itself an allocation (oom_reply.h).
    sendUnderPressure(request, 503, "{\"error\":\"out of memory building the response, retry\"}");
    return;
  }
  request->send(code, "application/json", body);
}

// sendJsonStreamed() - the zero-copy chunked path for the heavy responses - now lives in
// json_response.h, because the queued stats jobs on the poller task need it too (DESIGN.md SS12.1,
// and cpu_yield.h for why serialising on that task was a watchdog problem as well as a heap one).

void sendError(AsyncWebServerRequest *request, int code, const std::string &message, const std::string &path = "") {
  JsonDocument doc;
  doc["error"] = message;
  if (!path.empty()) {
    doc["path"] = path;
  }
  sendJson(request, code, doc);
}

// ---------------------------------------------------------------------------
// Authentication and cross-origin defence (DESIGN.md SS12; review F01/F05)
// ---------------------------------------------------------------------------

// THE single place a protected handler asks "may this request change something?". Every
// state-changing route calls requirePin() first and returns immediately if it answers false;
// there are deliberately no ad-hoc PIN comparisons anywhere else in this file, so the policy
// (which statuses, which bodies, the lockout) only ever has to be right once.
//
// The PIN travels in the custom header `X-Pin`, not a cookie and not a query parameter. That is
// what makes a blind cross-site POST harmless: a form or <img> from a malicious page can reach
// the device's LAN address, but the browser will not attach a custom header to a cross-origin
// request without a CORS preflight, and this server answers no preflight and sends no
// Access-Control-Allow-* header. A query parameter would land in browser history and server logs;
// a cookie would be sent automatically and re-open exactly the hole this closes.
constexpr const char *kPinHeader = "X-Pin";

// The status and body a rejected request gets. Kept as a value because the OTA upload handler
// decides at the first chunk (index == 0) but can only answer from its final handler.
struct ApiFailure {
  int status = 401;
  std::string message = "pin required";
  uint32_t retry_s = 0;  // 429 only
};

bool checkPin(AsyncWebServerRequest *request, ApiFailure &fail) {
  const AsyncWebHeader *h = request->getHeader(kPinHeader);
  auth::Check c = auth::check(h ? h->value().c_str() : nullptr);
  switch (c.result) {
    case auth::Result::Ok:
      return true;
    case auth::Result::Missing:
      fail = {401, "pin required", 0};
      return false;
    case auth::Result::Wrong:
      // The only record that a wrong PIN was presented, and the only thing that says WHICH route
      // presented it. auth.cpp logs the lockout itself, but by then five attempts have already
      // happened and the interesting question - who sent them - is unanswerable. A device-suite
      // run on 2026-09-16 produced eleven `PUT 429`s with nothing in the suite sending a wrong
      // PIN, and there was no evidence on the console to say otherwise because this line did not
      // exist and auth.cpp's was compiled out (CORE_DEBUG_LEVEL=1). Plain Serial.printf for that
      // reason; see auth.cpp.
      Serial.printf("[auth] wrong PIN on %s %s\n", request->methodToString(), request->url().c_str());
      fail = {401, "wrong pin", 0};
      return false;
    case auth::Result::Locked:
    default:
      fail = {429, "too many attempts", c.retry_s};
      return false;
  }
}

void sendFailure(AsyncWebServerRequest *request, const ApiFailure &fail) {
  // Formatted on the stack, not through a JsonDocument + String: a 401/429 must still go out
  // when the heap is momentarily exhausted (the device suite saw a 401 turn into a 503 "out of
  // memory building the response" while the poller was mid-fetch). The message is one of this
  // file's own literals, never user input, so no escaping is needed.
  char body[96];
  if (fail.status == 429) {
    snprintf(body, sizeof body, "{\"error\":\"%s\",\"retry_s\":%u}", fail.message.c_str(), (unsigned)fail.retry_s);
  } else {
    snprintf(body, sizeof body, "{\"error\":\"%s\"}", fail.message.c_str());
  }
  // Through sendUnderPressure() for the same reason the buffer is on the stack: this answer has to
  // go out when the heap is momentarily exhausted, and request->send() itself allocates the
  // response object (oom_reply.h). `body` is stack memory and is copied by the send.
  sendUnderPressure(request, fail.status, body);
}

// What every protected handler calls as its first statement: answers the request itself and
// returns false when the caller may not proceed.
bool requirePin(AsyncWebServerRequest *request) {
  ApiFailure fail;
  if (checkPin(request, fail)) return true;
  sendFailure(request, fail);
  return false;
}

// The device name, lower-cased. Kept here rather than read from getActiveConfig() on every
// request: hostAllowed() runs before every handler, and copying the whole Config (eight stops of
// std::strings) per request on a 75 KB heap is real churn for one field. Written only by
// setHostName() - from startWebServer() and the PUT /api/config handler, both on the async web
// server's own task, so no lock is needed.
//
// A char array rather than a std::string, and that is not a style choice: hostAllowed() is now
// called from HostGuardHandler::canHandle(), which the library invokes from inside `_parseLine`
// with no `try` above it anywhere. It must not allocate, because a std::bad_alloc escaping from
// there is std::terminate - the very reboot this pass removed from the middleware chain. The old
// version allocated twice per request (a std::string of the header, and `g_host_name + ".local"`).
char g_host_name[kMaxHostChars + 1] = {0};

void setHostName(const std::string &name) { storeHostName(name.c_str(), g_host_name, sizeof g_host_name); }

// DNS rebinding defence (review F05). A page on the public internet can make the browser resolve
// its own hostname to 192.168.1.x and then talk to this device with the *attacker's* origin -
// which defeats same-origin policy entirely, because as far as the browser is concerned the
// device is the attacker's site. The one thing the attacker cannot forge is the Host header: it
// carries their domain, not ours. So every request must name the device by one of the ways the
// owner can legitimately reach it, and anything else gets 421 (Misdirected Request) before a
// handler runs.
//
// The string work is in host_match.h, where `pio test -e native -f test_host_match` can reach it.
// Everything here is fixed buffers and integer compares: no allocation, nothing that can throw.
// The IP comparison is numeric (IPAddress::fromString) rather than against
// WiFi.localIP().toString(), because Arduino's String has no small-string buffer - that call
// malloc()s on every request, which is exactly what this must not do.
bool hostAllowed(const AsyncWebServerRequest *request) {
  const String &raw = request->host();  // by reference: the library owns it, no copy
  char host[kMaxHostChars + 1];
  // HTTP/1.1 requires a Host header; a client without one, or with one too long to be any name
  // this device answers to, is not the web UI.
  if (normalizeHost(raw.c_str(), raw.length(), host, sizeof host) == 0) return false;

  if (hostIsAlwaysAllowed(host)) return true;  // ssh tunnel / setup AP
  const IPAddress own = WiFi.localIP();
  IPAddress parsed;
  // `own != 0.0.0.0` matters: with no STA address yet, localIP() is all zeros and a request
  // claiming `Host: 0.0.0.0` would otherwise be accepted as "us".
  if (own != IPAddress((uint32_t)0) && parsed.fromString(host) && parsed == own) return true;
  return hostNamesDevice(host, g_host_name);
}

// Admission floor for the heap-heavy read handlers (/api/state copies the whole Snapshot plus
// weather and bike views into a JsonDocument; /api/config serializes the whole config): refuse with
// a fixed-literal 503 (needs almost no heap) when memory is clearly too low to build the response.
// Until 2026-09-16 this was the only defence against the uncatchable OOM-while-throwing reboot
// (device suite, 2026-09-15: bad_alloc in getBikes() <- handleGetState under load, with this SDK's
// zero-byte emergency exception pool). Now that cxx_exception_pool.cpp gives libstdc++ a pool the
// throw is catchable and guarded() answers 503 either way, so the gate is about cost, not safety: a
// build that is going to fail burns CPU and heap the poller wants, and the client retries a 503 just
// the same. It is deliberately NOT set high enough to "guarantee" a build under a concurrent
// allocation on the other core - an entry check cannot, since the poller shares this heap and can
// drop it mid-build - because a high floor just makes /api/state 503 for a long time after the heap
// fragments (largest block ~12 KB), while the build itself needs only 1 KB ArduinoJson pools and,
// since the zero-copy response (sendJsonStreamed), no body-sized contiguous block at all. The small
// handlers (debug/ui, tap, oom) are deliberately not gated: they cost little and the test/UI use
// them to observe the device precisely while it is under pressure.
//
// Both halves read MALLOC_CAP_8BIT since 2026-09-16 (DESIGN.md SS2.1). The free half used to read
// ESP.getFreeHeap() = heap_caps_get_free_size(MALLOC_CAP_INTERNAL), which on this chip includes
// ~34 KB of 32-bit-word-only IRAM heap that malloc() never hands out for a string or a buffer.
// INTERNAL free therefore never falls below that ~34 KB, so a 24 KB INTERNAL floor could not fire
// at all: the gate had been running on its largest-block half alone. 12 KB is derived from what the
// build actually takes out of the byte-addressable heap - a Config copy (~3 KB of small strings), a
// Snapshot copy, ArduinoJson's 1 KB slot pools plus its string pool for a ~4 KB document (~6 KB),
// and one 2,872 B send buffer - and is deliberately set below that total, per the paragraph above:
// the floor exists to skip a hopeless build, not to promise a successful one. The block half stays
// at 8 KB, already 2.8x the only contiguous allocation on the path (ASYNC_RESPONCE_BUFF_SIZE =
// CONFIG_LWIP_TCP_MSS * 2 = 2,872 B), the slack covering ArduinoJson's string pool.
//
// 7,924 rather than 8,192, and the odd-looking number is the point - see kMinOtaLargestBlock for
// the lattice this avoids. A round 8 KB sits 12 B above a real resting value (8,180), which is the
// worst placement available.
constexpr size_t kMinHeavyResponseFree8 = 12 * 1024;
constexpr size_t kMinHeavyResponseBlock = 7924;
bool refuseIfLowHeap(AsyncWebServerRequest *request) {
  if (heap_caps_get_free_size(MALLOC_CAP_8BIT) >= kMinHeavyResponseFree8 &&
      heap_caps_get_largest_free_block(MALLOC_CAP_8BIT) >= kMinHeavyResponseBlock) {
    return false;
  }
  // By definition the heap is already under the floor here, so this is the reply most likely to
  // fail to be built at all (oom_reply.h).
  sendUnderPressure(request, 503, "{\"error\":\"low memory, retry\"}");
  return true;
}

void handleGetState(AsyncWebServerRequest *request) {
  if (refuseIfLowHeap(request)) return;
  JsonDocument doc;
  doc["time"] = (int64_t)time(nullptr);
  doc["uptime"] = (uint32_t)(millis() / 1000);
  // Three heap numbers, and only the first is the historical one. `heap` stays ESP.getFreeHeap()
  // (MALLOC_CAP_INTERNAL) because clients parse it - firmware/test/device/exhaustive_test.py, the
  // web app, anyone's script - and silently changing what a published field means is worse than an
  // optimistic number. `heap_8bit` is what an allocation can really get, and it is the one the web
  // app shows and the gates in this file read; `largest_block_8bit` is the contiguous figure the
  // OTA gate turns away on, so a refused upload can be explained without the serial cable.
  // The difference between `heap` and `heap_8bit` is the 32-bit-word-only IRAM heap, ~34 KB on this
  // build, which malloc() never returns for a buffer or a string (DESIGN.md SS2.1).
  doc["heap"] = ESP.getFreeHeap();
  doc["heap_8bit"] = heap_caps_get_free_size(MALLOC_CAP_8BIT);
  doc["largest_block_8bit"] = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);

  Config cfg = getActiveConfig();

  JsonObject wifi = doc["wifi"].to<JsonObject>();
  wifi["ssid"] = WiFi.SSID();
  wifi["rssi"] = WiFi.RSSI();
  wifi["ip"] = WiFi.localIP().toString();
  wifi["mdns"] = cfg.device.name + ".local";

  SdStatus sd = getSdStatus();
  JsonObject sdj = doc["sd"].to<JsonObject>();
  sdj["mounted"] = sd.mounted;
  sdj["free_mb"] = (double)sd.free_bytes / (1024.0 * 1024.0);
  sdj["log_bytes"] = logBytes();
  // LittleFS (config + proxied bodies) occupancy, so a full filesystem is visible before saves fail.
  JsonObject fsj = doc["fs"].to<JsonObject>();
  fsj["used_kb"] = (uint32_t)(LittleFS.usedBytes() / 1024);
  fsj["total_kb"] = (uint32_t)(LittleFS.totalBytes() / 1024);
  sdj["dropped_rows"] = sd.dropped_rows;  // F26: rows that did not land on the card since boot
  sdj["write_ok"] = sd.last_write_ok;
  sdj["error"] = sd.error;

  PollStatus poll = getPollStatus();
  JsonObject last_poll = doc["last_poll"].to<JsonObject>();
  last_poll["ok"] = poll.ok;
  // -1 (never polled yet) vs. a real, non-negative age in seconds.
  last_poll["age_s"] = poll.has_polled ? (int32_t)((uint32_t)time(nullptr) - poll.last_poll_epoch) : (int32_t)-1;
  last_poll["error"] = poll.last_error;
  // DESIGN.md SS12.1: seconds since a cycle last COMPLETED, whatever its outcome - which is what
  // the liveness net watches, and is NOT age_s (that one only moves on a poll that reported).
  // -1 before the first cycle of this boot.
  {
    PollerLiveness lv = getPollerLiveness();
    last_poll["since_s"] = (lv.armed && !lv.before_first_cycle) ? (int32_t)(lv.since_ms / 1000U) : (int32_t)-1;
  }

  // DESIGN.md SS12.1: why the previous boot ended. `esp` is esp_reset_reason() - 1 ESP_RST_POWERON,
  // 2 ESP_RST_EXT, 3 ESP_RST_SW (what ESP.restart() produces), 4 ESP_RST_PANIC, 5/6 the interrupt
  // and task watchdogs, 9 ESP_RST_BROWNOUT - which is what distinguishes a panic from a clean
  // restart. `reason` is set only when THIS firmware restarted itself on purpose, and is ""
  // otherwise. `detail` is formatted here rather than stored, so the strings cost flash once.
  {
    JsonObject lr = doc["last_restart"].to<JsonObject>();
    lr["esp"] = (int)esp_reset_reason();
    RestartNote note = getRestartNote();
    char detail[96];
    detail[0] = '\0';
    const char *reason = "";
    if (note.reason == SelfHeal::PollStall) {
      reason = "poll_stall";
      snprintf(detail, sizeof(detail), "no poll cycle completed for %u s (interval %u s)", (unsigned)note.a, (unsigned)note.b);
    } else if (note.reason == SelfHeal::HeapWedge) {
      reason = "heap_wedge";
      snprintf(detail, sizeof(detail), "%u failed polls, largest free block %u B", (unsigned)note.a, (unsigned)note.b);
    } else if (note.reason == SelfHeal::HeapOom) {
      reason = "heap_oom";
      snprintf(detail, sizeof(detail), "%u consecutive out-of-memory polls, largest free block %u B", (unsigned)note.a, (unsigned)note.b);
    } else if (note.reason == SelfHeal::Nightly) {
      reason = "nightly";
      snprintf(detail, sizeof(detail), "scheduled nightly restart at %02u:%02u after %u h up",
               (unsigned)(note.a / 60), (unsigned)(note.a % 60), (unsigned)(note.b / 3600));
    } else if (note.reason == SelfHeal::LvglPool) {
      reason = "lvgl_pool";
      snprintf(detail, sizeof(detail), "LVGL pool exhausted: %u B free, %u B high-water", (unsigned)note.a, (unsigned)note.b);
    }
    lr["reason"] = reason;
    lr["detail"] = detail;
    lr["uptime_s"] = note.uptime_s;
  }

  doc["firmware_version"] = FIRMWARE_VERSION;
  // The board this image was built for (DESIGN.md SS7). Also what POST /api/ota refuses a
  // mismatching upload against, so the web UI can name it in the error it shows.
  doc["board"] = BOARD_NAME;
  // SS7: so the web UI can say "this needs the PIN" before it makes the user fill in a form, and
  // so a future build could report false if the owner ever turns the PIN off.
  doc["auth"]["pin_required"] = true;
  // SS6 safe-save: true when the last boot had to fall back to /config.prev.json because
  // /config.json was missing or unreadable. The UI surfaces it; nothing else changes.
  doc["config_recovered"] = configRecovered();
#ifdef TRANSIT_HTTPS
  {  // DESIGN.md SS2.1: which transport the poller is actually getting, so the UI can say so.
    const TransportStats ts = transportStats();
    JsonObject tr = doc["transport"].to<JsonObject>();
    tr["policy"] = transportName(transportPolicy());
    tr["last"] = ts.last;
    tr["https_ok"] = ts.https_ok;
    tr["https_failed"] = ts.https_failed;
    tr["cert_failed"] = ts.cert_failed;
    tr["http_by_heap"] = ts.http_by_heap;
    tr["http_by_policy"] = ts.http_by_policy;
    tr["refused_by_heap"] = ts.refused_by_heap;
    tr["last_tls_error"] = ts.last_tls_error;
    tr["last_https_ms"] = ts.last_https_ms;
    tr["heap_need"] = (uint32_t)tlsHeapNeed();
    tr["gate_free"] = (uint32_t)ts.gate_free;
    tr["gate_largest"] = (uint32_t)ts.gate_largest;
  }
#endif

  // NB: doc.as<JsonObject>(), not .to<JsonObject>() - the latter clears the
  // document, which would wipe the time/uptime/heap/wifi/sd/last_poll
  // fields set above (doc's root is already an object at this point).
#ifdef DEMO_DATA
  // Kept behind a compile flag for screen work without live SEPTA data/hardware (DESIGN.md SS3);
  // default off - see firmware/README.md.
  Snapshot snap = buildDemoSnapshot((transit::Epoch)time(nullptr));
  serializeSnapshot(snap, cfg, doc.as<JsonObject>());
#else
  // snapshotPtr(), and not a copy: this handler only READS the Snapshot, and borrowing the
  // poller's own costs neither a copy of every arrival in it nor a contiguous block to put that copy
  // in. On a device whose largest free block sits at 5 KB between polls that difference is the
  // difference between answering and answering 503 (DESIGN.md SS12.1), and it is also a whole
  // Snapshot less peak heap when four of these arrive at once.
  std::shared_ptr<const Snapshot> snap = snapshotPtr();
  static const Snapshot kNoSnapshot;
  serializeSnapshot(snap ? *snap : kNoSnapshot, cfg, doc.as<JsonObject>());
#endif

  sendJsonStreamed(request, doc);
}

void handleGetConfig(AsyncWebServerRequest *request) {
  if (refuseIfLowHeap(request)) return;
  Config cfg = getActiveConfig();
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJsonStreamed(request, doc);
}

// True when the parts of the config that decide what is fetched differ (stops, weather, bike).
bool dataSettingsChanged(const Config &a, const Config &b) {
  if (a.stops.size() != b.stops.size()) return true;
  for (size_t i = 0; i < a.stops.size(); ++i) {
    const transit::StopConfig &x = a.stops[i], &y = b.stops[i];
    if (x.key != y.key || x.stop_id != y.stop_id || x.route != y.route || x.station != y.station || x.direction != y.direction ||
        x.lat != y.lat || x.lng != y.lng || x.mode != y.mode) {
      return true;
    }
  }
  if (a.weather.enabled != b.weather.enabled || a.weather.per_stop != b.weather.per_stop || a.weather.fahrenheit != b.weather.fahrenheit) return true;
  if (a.bike.enabled != b.bike.enabled || a.bike.stations.size() != b.bike.stations.size()) return true;
  for (size_t i = 0; i < a.bike.stations.size(); ++i) {
    if (a.bike.stations[i].id != b.bike.stations[i].id) return true;
  }
  if (a.alerts != b.alerts || a.device.poll_seconds != b.device.poll_seconds || a.device.tz != b.device.tz) return true;
  return false;
}

void handlePutConfigInner(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged);

void handlePutConfig(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged) {
  if (!requirePin(request)) return;
  // Runs on the AsyncTCP task with the poller possibly mid-fetch: building a Config (strings,
  // vectors) can throw bad_alloc under that pressure, and an uncaught throw is a reboot (see
  // net_poller.cpp pollOnce). A 503 lets the browser retry a moment later.
  try {
    handlePutConfigInner(request, json, onConfigChanged);
  } catch (const std::bad_alloc &) {
    request->send(503, "application/json", "{\"error\":\"out of memory, retry\"}");
  }
}

void handlePutConfigInner(AsyncWebServerRequest *request, JsonVariant &json, const std::function<void(bool)> &onConfigChanged) {
  Config cfg;
  ConfigError err;
  if (!jsonToConfig(json, cfg, err)) {
    sendError(request, 400, err.message, err.path);
    return;
  }
  if (!saveConfig(cfg)) {
    sendError(request, 500, "failed to write config to LittleFS");
    return;
  }
  bool data_changed = dataSettingsChanged(getActiveConfig(), cfg);
  setActiveConfig(cfg);
  setHostName(cfg.device.name);  // a rename changes which Host headers are accepted (review F05)
  if (onConfigChanged) {
    onConfigChanged(data_changed);
  }
  // Same streamed response as GET /api/config: the 16 KB request document is still alive here, so
  // this is the moment a second body copy hurt most (SS12.1).
  JsonDocument doc;
  configToJson(cfg, doc);
  sendJsonStreamed(request, doc);
}

// DESIGN.md SS7: POST /api/pin, body {"pin":"new"}, authenticated with the CURRENT pin in X-Pin.
// There is deliberately no "forgot my PIN" endpoint: the recovery path is physical (the serial
// console at boot, or the device info screen), see auth.h.
void handlePostPin(AsyncWebServerRequest *request, JsonVariant &json) {
  if (!requirePin(request)) return;
  JsonVariantConst body = json;
  if (!body["pin"].is<const char *>()) {
    sendError(request, 400, "body must be {\"pin\":\"...\"}", "pin");
    return;
  }
  std::string next = std::string(body["pin"].as<const char *>());
  std::string error;
  if (!auth::setPin(next, error)) {
    sendError(request, 400, error, "pin");
    return;
  }
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
}

void handlePostReboot(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  scheduleRestart();
}

void handlePostWifiReset(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  JsonDocument doc;
  doc["ok"] = true;
  sendJson(request, 200, doc);
  // Enable STA, erase the ESP-IDF's persisted Wi-Fi credentials, then reboot so main.cpp's
  // wifi_portal::connectWifiOrPortal() finds nothing to reconnect with and opens the setup AP.
  WiFi.mode(WIFI_STA);
  WiFi.disconnect(true, true);
  scheduleRestart();
}

// DESIGN.md SS7/SS12: "POST /api/ota; multipart `firmware` field; reboots on success."
//
// The whole upload is one transaction with an explicit outcome (review F08). The old version
// started from g_ota_ok = true, so a POST that never delivered a byte - no file part, a client
// that vanished, an unauthorised caller - answered 200 and rebooted into whatever was in the OTA
// slot. Now nothing is "ok" until the final chunk has been seen AND Update.end(true) has
// succeeded AND the image proved it was built for this board.
//
// Admission checks happen at index == 0, before Update.begin(), because that is the last moment
// at which refusing costs nothing: after it, ~1.7 MB is already on the wire.
// Both numbers are MALLOC_CAP_8BIT since 2026-09-16, and both were re-derived from what the OTA
// path actually allocates rather than from the INTERNAL figure they had been tuned against
// (DESIGN.md SS2.1). What Update takes off the byte-addressable heap is exactly one buffer:
// Update.begin() does `new (std::nothrow) uint8_t[SPI_FLASH_SEC_SIZE]` = 4,096 B (Updater.cpp), and
// the only other allocation on the path is a 16 B _skipBuffer at the first written sector. Nothing
// in Update.write() is body-sized: ESPAsyncWebServer hands the multipart body over in ~1.4 KB
// pieces and Update buffers them into that one sector.
//
// The old pair - 60 KB of INTERNAL free and a 16 KB block - is why an upload could not get in while
// the device was polling. On 2026-09-16 every attempt was refused for ten minutes ("largest free
// block 15 KB is below 16 KB" between polls, "free heap 4x KB is below 60 KB" during them) and a
// reboot-then-upload or the serial cable was the only way in. Neither threshold described a real
// requirement: 16 KB is 4x the one 4,096 B block Update asks for, and 60 KB of INTERNAL is ~26 KB
// of byte-addressable heap, which sits inside the band a poll leaves behind, so the gate flapped
// with the poll cycle. Measured over 114 samples on the owner's cyd-3248S035R, the 8-bit largest
// block sits at 20,468 B for most of the cycle - comfortably past 16 KB - but drops to 14,324 B and
// as far as 8,692 B while a poll is decoding a feed, which is exactly when someone reaches for an
// update. That dip refused 30 of 114 attempts on the block half alone, and another 9 on the free
// half: 34% of the time, for a 4,096 B allocation that would have succeeded in every one of them.
//
// So: 6 KB of largest block, 1.5x the 4,096 B buffer, which clears the measured 8,692 B floor with
// room and still refuses a heap fragmented past the point where that buffer could land; and 16 KB
// of 8-bit free for the request machinery and the rest of the device to keep working beside it.
// The alternative - having the handler wait for the poller's idle gap - was rejected: index == 0
// runs on the AsyncTCP task, and blocking there stalls every other connection, which is a worse
// failure than the one being fixed, while the client is already mid-upload with ~1.7 MB to push.
constexpr size_t kMinOtaFree8 = 16 * 1024;
// Update.write() needs a contiguous scratch buffer; free heap alone can be healthy while the
// largest block is fragmented down to a few KB, which is how a mid-flash failure used to happen
// on a device that had been up for days (firmware/README.md, "Memory and flash budget").
//
// 5,876 and not 6 * 1024, which looks arbitrary and is not. This allocator hands out largest-block
// sizes on a 512-byte lattice at offset 500 - every one of 24 distinct values measured here fits
// `500 + 512k` exactly, and desktop-c8 and desktop-e9 confirmed the same structure independently
// across four images. ANY multiple of 512 therefore lands exactly 12 B above a lattice point, since
// 512 - 500 = 12 puts the point below 512m at 512m - 12 for every m - the worst placement there is:
// a device resting on that point is refused by a hair, and the next value up clears by 1,012 B.
// That catches more than round kilobytes; 5,632 and 7,680 are just as bad. That is not a hypothetical. It is why the old 16,384 B
// gate locked out a v0.2.0 board resting at 16,372, and resting values of 8,180 and 12,276 were
// observed against the other two round thresholds.
//
// Note m * 1024 - 512 does NOT fix it: 5,632 is itself a multiple of 512 and sits 12 B above 5,620,
// the same pathology one residue over. Mid-gap on a 512 lattice at offset 500 is `756 + 512k`,
// which is not a multiple of 512 and is 256 B from either
// neighbour - so a build resting on any lattice point is admitted or refused with real margin, and
// a small change in allocation cannot flip admission. 5,876 is still 1.43x the single 4,096 B
// buffer this gate exists to protect.
constexpr size_t kMinOtaLargestBlock = 5876;

// Board identity, stamped into .rodata of every build and therefore into every firmware.bin
// (review F08: there is no firmware signing, but flashing a 2.4"-capacitive image onto a 3.5"
// resistive board bricks the display until someone reaches it with a USB cable). The upload is
// searched for the RUNNING device's own marker; the trailing ';' is part of the pattern so
// "cyd-2432S028R;" cannot match inside "cyd-2432S028Rv3;". `used` keeps the compiler from
// dropping it; it is referenced below anyway, which is what keeps the linker from doing so.
const char kBoardMarker[] __attribute__((used, section(".rodata"))) = "PTD-BOARD:" BOARD_NAME ";";
constexpr size_t kBoardMarkerLen = sizeof(kBoardMarker) - 1;

struct OtaState {
  const void *owner = nullptr;  // the request whose outcome this struct describes
  bool busy = false;            // a flash-writing upload is in progress
  bool writing = false;         // Update.begin() succeeded and Update.end() has not run yet
  bool ok = false;              // F08: starts false, set only when everything has succeeded
  bool final_seen = false;
  int status = 500;
  std::string error;
  uint32_t retry_s = 0;  // set with status 429 (PIN lockout), so the final handler can repeat it
  size_t written = 0;
  size_t marker_match = 0;  // how many bytes of kBoardMarker the stream has matched so far
  bool marker_found = false;
};
OtaState g_ota;

// The OTA slot is the hard ceiling on the image: Update would fail late with "Not enough space",
// after the whole upload has been drained. Knowing the size up front lets the transfer be cut off
// as soon as it is provably too big.
size_t otaSlotSize() {
  const esp_partition_t *running = esp_ota_get_running_partition();
  return running != nullptr ? running->size : 0;
}

void otaFail(int status, const std::string &message) {
  g_ota.ok = false;
  g_ota.status = status;
  g_ota.error = message;
  if (g_ota.writing) {
    Update.abort();
    g_ota.writing = false;
  }
  g_ota.busy = false;
}

// Releases the transaction when the client goes away (review F08: without this a client that
// disconnects mid-upload leaves `busy` set forever and Update holding the partition, so every
// later OTA answers 409 until the device is rebooted).
void otaRelease(const void *owner) {
  if (g_ota.owner != owner) return;  // a newer upload already took over; leave its state alone
  if (g_ota.writing) {
    log_w("web_server: OTA client disconnected mid-image, aborting");
    Update.abort();
    g_ota.writing = false;
    g_ota.ok = false;
    g_ota.status = 400;
    g_ota.error = "upload disconnected before the image was complete";
  }
  g_ota.busy = false;
}

// Streaming search for kBoardMarker. The marker can straddle any two chunks, so the match length
// carries across calls; on a mismatch it backs off to the longest prefix of the marker that is
// still a suffix of what was matched (a hand-rolled KMP step - the fallback loop only runs on the
// rare mismatch-after-partial-match, so it costs nothing on the ~1.7 MB happy path).
void otaScanForMarker(const uint8_t *data, size_t len) {
  if (g_ota.marker_found) return;
  size_t m = g_ota.marker_match;
  for (size_t i = 0; i < len; ++i) {
    uint8_t b = data[i];
    while (m > 0 && (uint8_t)kBoardMarker[m] != b) {
      size_t k = m - 1;
      while (k > 0 && memcmp(kBoardMarker, kBoardMarker + m - k, k) != 0) --k;
      m = k;
    }
    if ((uint8_t)kBoardMarker[m] == b) ++m;
    if (m == kBoardMarkerLen) {
      g_ota.marker_found = true;
      g_ota.marker_match = 0;
      return;
    }
  }
  g_ota.marker_match = m;
}

// The body of the upload callback. Never called directly - handleOtaUpload() wraps it, because
// nothing in ESPAsyncWebServer catches what escapes from here.
void otaUploadStep(AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final) {
  if (index == 0) {
    if (g_ota.busy && g_ota.owner != request) {
      // Someone else is already flashing. Do not touch their state; handlePostOta() answers 409
      // for this request because it never becomes the owner.
      return;
    }
    g_ota = OtaState{};
    g_ota.owner = request;
    g_ota.status = 500;
    // Fires on client disconnect, including the normal end of the request, so the transaction is
    // released on every path out of here.
    request->onDisconnect([request]() { otaRelease(request); });

    // The Host check that used to be repeated here is gone, and its absence is the point.
    // HostGuardHandler (below) does it from `canHandle()`, which the library calls at END OF
    // HEADERS - before this callback exists to be called. A DNS-rebound upload is claimed by that
    // handler and never becomes an OTA request at all, so it cannot reach Update.begin() or a
    // single Update.write(). The old duplication was needed only because the check lived in the
    // middleware chain, which does not run until the whole body has been parsed; that is no longer
    // where it lives. Do not put it back without checking that first - two copies of a security
    // check drift, and the one that drifts is the copy nobody's test exercises.
    ApiFailure fail;
    if (!checkPin(request, fail)) {
      // Unauthorised: record the outcome, write nothing, and hang up rather than politely
      // draining 1.7 MB of an attacker's upload through a device with 75 KB of heap. The final
      // handler replays `fail` as the response if the close still lets one out.
      g_ota.ok = false;
      g_ota.status = fail.status;
      g_ota.error = fail.message;
      g_ota.retry_s = fail.retry_s;
      g_ota.busy = false;
      if (request->client() != nullptr) request->client()->close();
      return;
    }

    log_w("web_server: OTA upload starting: %s", filename.c_str());
    // Both the measurement and the message say "8-bit": the refusal text is what someone reads at
    // 2 a.m. with a device that will not take an image, and it has to name the same number they can
    // go and check in /api/state's heap_8bit. The thresholds are printed from the constants rather
    // than spelled out, so a future re-derivation cannot leave the message lying.
    //
    // Every refusal ends with the way out, because a refusal that does not is how a device gets
    // stranded - and the old 16 KB block threshold stranded real builds, both measured 2026-09-16
    // on the owner's two-stop config:
    //
    //   3707f54          resting largest block 11,764 B   5 attempts over 10 min, all refused
    //   released v0.2.0  resting largest block 16,372 B   3 attempts, all refused
    //
    // Neither is a dip during a poll; both are the steady state. v0.2.0 is the more unsettling of
    // the two because it misses the old 16,384 B threshold by **twelve bytes** - 0.07% - which is
    // not a build that sits comfortably under the line but one that happens to land on the wrong
    // side of it. Do not read that as "v0.2.0 devices are lockable" in general: a different stop
    // list or feed selection moves resting fragmentation either way, and over-widening a measured
    // result to a whole population is the same mistake this comment already had to correct once.
    //
    // The thresholds below are low enough that neither build would be refused now, but "would not"
    // is not "cannot": a long-lived device can always fragment past any floor, and at that point
    // the only lever the owner has is a restart. It is not taken automatically - this is a display
    // on someone's wall and a failed upload is not a reason to blank it - so the message says it
    // and the owner decides. The message says "within the first minute" because the escape window
    // is build-dependent and can be short: 3707f54 reboots to 23,540 B and stays there, but v0.2.0
    // returns to its resting 16,372 B about 45 s after boot (an upload at uptime 13 s returned 200).
    const std::string kRetryHint = "; restart the device (Settings, or POST /api/reboot) and upload"
                                   " again within the first minute - a freshly booted heap is"
                                   " unfragmented and does not stay that way";
    // Bytes, not rounded kilobytes. The old message said "largest free block 15 KB is below 16 KB"
    // on a v0.2.0 device that was actually 16,372 B against 16,384 - twelve bytes short. Integer
    // division turned a knife edge into what read like a comfortable kilobyte, and anyone debugging
    // it would go hunting for what was eating 1 KB. A number a human is expected to act on gets
    // reported exactly (found by desktop-c8's v0.2.0 measurement, 2026-09-16).
    size_t free8 = heap_caps_get_free_size(MALLOC_CAP_8BIT);
    size_t largest = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
    if (free8 < kMinOtaFree8) {
      otaFail(503, "refusing OTA: 8-bit free heap " + std::to_string(free8) + " B is below " +
                     std::to_string(kMinOtaFree8) + " B" + kRetryHint);
      return;
    }
    if (largest < kMinOtaLargestBlock) {
      otaFail(503, "refusing OTA: largest 8-bit free block " + std::to_string(largest) + " B is below " +
                     std::to_string(kMinOtaLargestBlock) + " B" + kRetryHint);
      return;
    }
    if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.busy = true;
    g_ota.writing = true;
    g_ota.ok = true;
  }

  if (g_ota.owner != request || !g_ota.writing) return;  // rejected above; ignore the bytes

  if (len > 0) {  // the final call can carry no bytes at all
    size_t slot = otaSlotSize();
    if (slot != 0 && g_ota.written + len > slot) {
      otaFail(413, "firmware image is larger than the " + std::to_string(slot) + " byte OTA slot");
      if (request->client() != nullptr) request->client()->close();
      return;
    }
    if (Update.write(data, len) != len) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.written += len;
    otaScanForMarker(data, len);
  }

  if (final) {
    g_ota.final_seen = true;
    // The board check runs BEFORE Update.end(): an image for another board is a valid ESP32 image
    // and would pass end()'s own checks, and once end() has run the partition is marked bootable.
    if (!g_ota.marker_found) {
      otaFail(400, std::string("firmware is for a different board (expected ") + BOARD_NAME + ")");
      return;
    }
    if (!Update.end(true)) {
      otaFail(500, Update.errorString());
      return;
    }
    g_ota.writing = false;
    g_ota.busy = false;
  }
}

// ESPAsyncWebServer's upload callback, and the one thing every other route gets from guarded()
// but this one cannot (DESIGN.md SS12.1).
//
// Catch here. Nothing in the library catches what escapes an upload callback - `handleUpload` is
// invoked from inside `_parseLine`, with no `try` anywhere above it - so without this a bad_alloc
// anywhere in the step would be std::terminate and a reboot. guarded() does the same job for the
// ordinary handlers and cannot reach this one, because guarded() wraps `handleRequest`, which runs
// after the whole body. The refusal text is short on purpose - 13 characters fits libstdc++'s
// small-string buffer, so recording it allocates nothing, which is the one property that matters
// in a catch block that runs because there was no memory.
//
// The warmExceptionGlobals() call that used to open this function is gone: HostGuardHandler's
// canHandle() runs at end of headers, i.e. before the first byte of the body reaches this
// callback, so by the time an upload starts the AsyncTCP task's __cxa_eh_globals have already been
// paid for on this very request. Before that handler existed the warming lived in the middleware
// chain, which does not run until the body is complete - which is why this callback had to repeat
// it. It no longer does, and the catch below is what makes the difference visible: this is the
// try/catch, and something else is now responsible for the throw being catchable at all.
void handleOtaUpload(AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len, bool final) {
  try {
    otaUploadStep(request, filename, index, data, len, final);
  } catch (const std::bad_alloc &) {
    if (g_ota.writing) {
      Update.abort();
      g_ota.writing = false;
    }
    g_ota.ok = false;
    g_ota.status = 503;
    g_ota.error = "out of memory";
    g_ota.busy = false;
    if (request->client() != nullptr) request->client()->close();
  }
}

void handlePostOta(AsyncWebServerRequest *request) {
  if (g_ota.owner == request) {
    if (!g_ota.ok) {
      sendFailure(request, ApiFailure{g_ota.status, g_ota.error.empty() ? "OTA failed" : g_ota.error, g_ota.retry_s});
      return;
    }
    if (!g_ota.final_seen) {
      // Update.end() was never reached: the multipart body ended without a final chunk.
      sendError(request, 400, "upload ended before the image was complete");
      return;
    }
    JsonDocument doc;
    doc["ok"] = true;
    doc["bytes"] = g_ota.written;
    doc["board"] = BOARD_NAME;
    sendJson(request, 200, doc);
    scheduleRestart();
    return;
  }
  // Never became the owner: either no file part arrived at all, or another upload holds the flash.
  if (!request->hasParam("firmware", true, true)) {
    sendError(request, 400, "no firmware file");
    return;
  }
  sendError(request, 409, "another firmware upload is in progress");
}

// DESIGN.md SS7 setup-wizard proxies: both just queue the job to proxy_worker.cpp's own task
// (never block the async web server's task on a SEPTA round trip) and return without responding -
// the worker calls request->send() itself once it has a result.
void handleProxyStops(AsyncWebServerRequest *request) {
  if (!request->hasParam("route")) {
    sendError(request, 400, "route is required");
    return;
  }
  queueStopsProxy(request, request->getParam("route")->value().c_str());
}

void handleProxySchedule(AsyncWebServerRequest *request) {
  if (!request->hasParam("stop_id")) {
    sendError(request, 400, "stop_id is required");
    return;
  }
  queueScheduleProxy(request, request->getParam("stop_id")->value().c_str());
}

// ---------------------------------------------------------------------------------------------
// The heap instrument's readout side (diag branch, 2026-09-17). heap_trace.h has the why.
//
// THE CONSTRAINT THAT SHAPES ALL OF THIS: /api/debug/ui is deliberately outside refuseIfLowHeap()
// and is the only endpoint that still answers on a board whose largest block is under 4 KB. The
// trace must therefore not be the thing that stops it answering. So the rows are rendered by hand
// into a fixed .bss buffer and injected with serialized(), NOT built as nested JsonArrays: 32 rows
// of four numbers would be ~160 ArduinoJson slots, i.e. two or three more 1,024 B pool chunks, and
// a pool that cannot grow makes the document overflow, which sendJson() correctly turns into a 503.
// ArduinoJson copies a serialized() value into one StringNode, so the added heap cost is a single
// contiguous block of what the rows actually measure - about 700 B at 32 rows - and nothing else.
//
// 32 rows and not the ring's full 64 for the same reason: the response body is copied twice on the
// way out (the serialised String, then AsyncBasicResponse's own copy of it), so every byte here is
// two contiguous bytes at the worst moment. A sampler passes `since` and gets only new rows, which
// is a few hundred bytes per poll; `?n=64` is there for a one-off full dump on a healthy board.
constexpr size_t kTraceMaxRows = 32;
// The per-cycle log (cycle_log.h) renders through the SAME buffer, and `?log=1` therefore returns
// the log INSTEAD of the stage trace rather than beside it. Two buffers would be ~1.3 KB more
// .bss for two instruments that are never read in the same breath: the trace answers "where
// inside this cycle", the log answers "which cycle", and an investigation moves from one to the
// other. A row is "[2592000,131072,131072,65535,127]," - 34 characters at the widest.
constexpr size_t kCycleLogMaxRows = 40;
constexpr size_t kLogRowBytes = 40;
// "[65535,22,1048576,1048576]," is 27 characters; 32 B a row is slack, not a measurement.
constexpr size_t kRenderBufBytes =
  (kTraceMaxRows * 32 > kCycleLogMaxRows * kLogRowBytes ? kTraceMaxRows * 32
                                                        : kCycleLogMaxRows * kLogRowBytes) + 8;
char g_trace_json[kRenderBufBytes];

const char *renderTrace(uint32_t since, size_t want, uint32_t *first_seq, size_t *count) {
  if (want == 0 || want > kTraceMaxRows) want = kTraceMaxRows;
  HeapTraceEntry rows[kTraceMaxRows];  // 384 B on the AsyncTCP task's 8 KB stack, freed on return
  size_t n = heapTraceRead(since, rows, want, first_seq);
  size_t at = 0;
  g_trace_json[at++] = '[';
  size_t written = 0;
  for (size_t i = 0; i < n; i++) {
    int w = snprintf(g_trace_json + at, sizeof(g_trace_json) - at - 2, "%s[%u,%u,%u,%u]", i ? "," : "",
                     (unsigned)rows[i].cycle, (unsigned)rows[i].stage, (unsigned)rows[i].free8,
                     (unsigned)rows[i].largest);
    if (w <= 0 || (size_t)w >= sizeof(g_trace_json) - at - 2) break;  // cannot happen at these widths
    at += (size_t)w;
    written++;
  }
  g_trace_json[at++] = ']';
  g_trace_json[at] = '\0';
  *count = written;
  return g_trace_json;
}

// The per-cycle memory log (cycle_log.h), rendered the same way and into the same buffer as the
// stage trace above and for the same reason: hand-written rows injected with serialized(), not
// nested JsonArrays, so /api/debug/ui does not become the endpoint that cannot answer on a starved
// heap. Row shape: [uptime_s, free8, largest, min_free8, flags] - min_free8 in BYTES here (the
// ring stores it in 64-byte units), because a reader should not have to know the scale.
const char *renderCycleLog(uint32_t since, size_t want, uint32_t *first_seq, size_t *count) {
  if (want == 0 || want > kCycleLogMaxRows) want = kCycleLogMaxRows;
  CycleLogEntry rows[kCycleLogMaxRows];  // 640 B on the AsyncTCP task's 8 KB stack, freed on return
  size_t n = cycleLogRead(since, rows, want, first_seq);
  size_t at = 0;
  g_trace_json[at++] = '[';
  size_t written = 0;
  for (size_t i = 0; i < n; i++) {
    int w = snprintf(g_trace_json + at, sizeof(g_trace_json) - at - 2, "%s[%u,%u,%u,%u,%u]",
                     i ? "," : "", (unsigned)rows[i].uptime_s, (unsigned)rows[i].free8,
                     (unsigned)rows[i].largest,
                     (unsigned)((uint32_t)rows[i].min_free8_64 * kMinFreeScale),
                     (unsigned)rows[i].flags);
    if (w <= 0 || (size_t)w >= sizeof(g_trace_json) - at - 2) break;  // cannot happen at these widths
    at += (size_t)w;
    written++;
  }
  g_trace_json[at++] = ']';
  g_trace_json[at] = '\0';
  *count = written;
  return g_trace_json;
}

// uxTaskGetStackHighWaterMark by task name: the smallest number of stack BYTES that task has ever
// had left (StackType_t is a byte on this port, which is why net_poller.cpp's own stack_free line
// reads in bytes too). Looked up by name rather than by a stored handle because two of the three
// tasks are not ours - "loopTask" is the Arduino core's and "async_tcp" is AsyncTCP's. A task that
// does not exist yet reports 0. Neither call allocates.
uint32_t taskStackHwm(const char *name) {
  TaskHandle_t h = xTaskGetHandle(name);
  return h == nullptr ? 0 : (uint32_t)uxTaskGetStackHighWaterMark(h);
}

uint32_t queryU32(AsyncWebServerRequest *request, const char *name, uint32_t fallback) {
  if (!request->hasParam(name)) return fallback;
  return (uint32_t)strtoul(request->getParam(name)->value().c_str(), nullptr, 10);
}

// DESIGN.md SS12.1: the deterministic on-device proof of the C++ emergency exception pool
// (cxx_exception_pool.cpp). Takes the heap away in shrinking blocks until even a 16-byte allocation
// fails, then forces a std::bad_alloc: with no pool, __cxa_allocate_exception cannot get the ~100
// bytes for the exception object and calls std::terminate - a reboot - before any catch block runs;
// with the pool it lands in the catch below. Every block is freed before the response is built, and
// the body is snprintf'd into a stack buffer so answering needs no heap of its own. "largest" is the
// largest free block at the moment of the throw: under ~100 bytes proves the exception object came
// from the pool and not from a hole another task opened meanwhile. PIN-gated because it starves
// every other task for the sub-millisecond it holds the blocks (the poller and the display loop
// catch their own bad_alloc and carry on; lwIP tolerates a NULL pbuf; LVGL draws from its own pool).
void handleDebugOom(AsyncWebServerRequest *request) {
  if (!requirePin(request)) return;
  constexpr size_t kMaxBlocks = 200;
  static const size_t kBlockSizes[] = {1024, 256, 64, 16};
  void *blocks[kMaxBlocks];
  size_t n = 0;
  const uint32_t free_before = ESP.getFreeHeap();
  for (size_t size : kBlockSizes) {
    while (n < kMaxBlocks) {
      void *p = heap_caps_malloc(size, MALLOC_CAP_8BIT);
      if (!p) break;
      blocks[n++] = p;
    }
  }
  const size_t largest = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);
  bool caught = false;
  char *volatile probe = nullptr;  // volatile: the compiler may otherwise elide an unused new/delete pair
  try {
    probe = new char[4096];
    delete[] probe;
  } catch (const std::bad_alloc &) {
    caught = true;
  }
  for (size_t i = 0; i < n; ++i) heap_caps_free(blocks[i]);
  char body[128];
  snprintf(body, sizeof body, "{\"caught\":%s,\"blocks\":%u,\"largest\":%u,\"free_before\":%u,\"free_after\":%u}",
           caught ? "true" : "false", (unsigned)n, (unsigned)largest, (unsigned)free_before, (unsigned)ESP.getFreeHeap());
  request->send(200, "application/json", body);
}

// Static list embedded in firmware (transit_core/rail_stations.h) - no network needed, so this
// runs directly on the web server's own task.
//
// Streamed, not sendJson()'d (audit_runtime SS5, ranked recommendation 6): 149 station names is a
// ~2-4 KB body, and sendJson() serialises it into a String and then hands that to
// AsyncBasicResponse, which copies it - two body-sized CONTIGUOUS blocks, on the device whose
// largest free block is the thing that runs out. sendJsonStreamed() moves the document into the
// response and serialises it straight into each 2,872 B send chunk, so the only contiguous block
// is that chunk buffer. Same reasoning, same helper, as /api/state and /api/config.
void handleRailStations(AsyncWebServerRequest *request) {
  if (refuseIfLowHeap(request)) return;
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (size_t i = 0; i < transit::kRailStationCount; ++i) {
    arr.add(transit::kRailStationNames[i]);
  }
  sendJsonStreamed(request, doc);
}

// DESIGN.md SS9.3: queued to proxy_worker.cpp's task since it streams one or more monthly CSV
// files off SD (never instant, and never something to do on the async server's own task).
void handleGetStats(AsyncWebServerRequest *request) {
  // Entry gate, like /api/state and /api/config: a queued job that cannot be started is worse
  // than a 503, because pausing the request turns its server-side timeout off (audit_runtime SS4).
  if (refuseIfLowHeap(request)) return;
  if (!request->hasParam("stop")) {
    sendError(request, 400, "stop is required");
    return;
  }
  std::string stop_key = request->getParam("stop")->value().c_str();
  int days = request->hasParam("days") ? atoi(request->getParam("days")->value().c_str()) : 30;
  queueStatsRequest(request, stop_key, days);
}

// DESIGN.md SS7: "[ { "file": "2026-09.csv", "bytes": 123456 } ]". Fast (a directory listing of
// at most a handful of monthly files), so this runs directly on the web server's own task.
void handleLogIndex(AsyncWebServerRequest *request) {
  JsonDocument doc;
  JsonArray arr = doc.to<JsonArray>();
  for (const LogFileInfo &f : listLogFiles()) {
    JsonObject o = arr.add<JsonObject>();
    o["file"] = f.name;
    o["bytes"] = f.bytes;
  }
  sendJson(request, 200, doc);
}

// GET /api/log/<file>.csv - only "YYYY-MM.csv" is accepted (guards against path traversal /
// reading anything else off the card, DESIGN.md SS12's "same posture as a printer" notwithstanding
// - there's no reason this endpoint should ever open a file other than one of its own logs).
// AsyncWebServer streams the returned File incrementally itself; this handler just opens it.
bool isLogFilename(const std::string &name) {
  // "YYYY-MM.csv": 4 digits, '-', 2 digits, ".csv" = 11 characters.
  if (name.size() != 11 || name.compare(7, 4, ".csv") != 0) return false;
  for (size_t i = 0; i < 7; ++i) {
    if (i == 4) {
      if (name[i] != '-') return false;
    } else if (!isdigit(static_cast<unsigned char>(name[i]))) {
      return false;
    }
  }
  return true;
}

bool handleLogDownload(AsyncWebServerRequest *request) {
  std::string url = request->url().c_str();
  const std::string prefix = "/api/log/";
  if (url.rfind(prefix, 0) != 0) return false;
  std::string filename = url.substr(prefix.size());
  // PIN-protected even though it only reads (DESIGN.md SS12): the CSV is a month of the owner's
  // movements - when they leave the house and which stop they leave from - which is the most
  // personal thing this device holds. `GET /api/log/index` (file names and sizes) stays open.
  if (!requirePin(request)) return true;
  if (!isLogFilename(filename)) {
    sendError(request, 400, "not a log filename");
    return true;
  }
  // One download at a time (F26): the SD mount allows two open files and the poller's append
  // needs one of them. The export re-emits every row in schema v3 (F24/F25) through a chunked
  // response; the reader lease is released by the response's completion/disconnect callback.
  if (!acquireLogReader()) {
    sendError(request, 503, "a log download is already running, try again");
    return true;
  }
  auto exp = std::make_shared<LogExport>(filename);
  if (!exp->ok()) {
    releaseLogReader();
    sendError(request, 404, "no log for that month");
    return true;
  }
  AsyncWebServerResponse *response = request->beginChunkedResponse(
      "text/csv", [exp](uint8_t *buf, size_t maxLen, size_t /*index*/) -> size_t {
        // Runs on the AsyncTCP task, outside guarded(); LogExport::fill() catches its own
        // bad_alloc, but wrap here too so no filler allocation can ever reach std::terminate.
        try {
          return exp->fill(buf, maxLen);
        } catch (const std::bad_alloc &) {
          return (size_t)0;  // ends the chunked response
        }
      });
  response->addHeader("Content-Disposition", (String("attachment; filename=\"") + filename.c_str() + "\"").c_str());
  request->onDisconnect([]() { releaseLogReader(); });
  request->send(response);
  return true;
}

#ifdef TRANSIT_HAVE_WEB_ASSETS
// DESIGN.md SS7/SS10: gzip, right content type, ETag = firmware build id (WEB_ASSETS_ETAG - a
// hash of the source assets, which is the closest stable per-build id we have without wiring a
// separate firmware build-id scheme), If-None-Match -> 304, Cache-Control max-age=3600 for the
// static assets and no-cache for "/" (its content never changes without a firmware update, but
// browsers should still re-validate it on every navigation so a stale service worker / bookmark
// doesn't hide an update the way max-age=3600 would for up to an hour).
void handleWebAsset(AsyncWebServerRequest *request, const transit_web::WebAsset &asset) {
  bool is_index = std::strcmp(asset.path, "/") == 0;

  if (request->hasHeader("If-None-Match")) {
    const AsyncWebHeader *inm = request->getHeader("If-None-Match");
    if (inm && inm->value() == transit_web::WEB_ASSETS_ETAG) {
      AsyncWebServerResponse *response = request->beginResponse(304);
      response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
      request->send(response);
      return;
    }
  }

  AsyncWebServerResponse *response = request->beginResponse(200, asset.content_type, asset.data, asset.len);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("ETag", transit_web::WEB_ASSETS_ETAG);
  response->addHeader("Cache-Control", is_index ? "no-cache" : "max-age=3600");
  if (is_index) {
    // Review F05, on the document that carries the app: a hostile page that frames this UI can
    // read nothing across origins, but it can bait clicks onto controls the owner cannot see.
    // Both headers say the same thing to old and new browsers. No script-src directive on
    // purpose - the Stops page loads Leaflet from a CDN (DESIGN.md SS10) and a CSP that forbids it
    // would break the map silently; the frame directives cost nothing and break nothing.
    response->addHeader("X-Frame-Options", "DENY");
    response->addHeader("Content-Security-Policy", "frame-ancestors 'none'");
    // The UI is served gzipped from PROGMEM with fixed content types; nosniff stops a browser
    // deciding for itself that one of them is something executable.
    response->addHeader("X-Content-Type-Options", "nosniff");
  }
  request->send(response);
}

void registerWebAssets() {
  for (size_t i = 0; i < transit_web::WEB_ASSETS_COUNT; ++i) {
    const transit_web::WebAsset &asset = transit_web::WEB_ASSETS[i];
    g_server.on(asset.path, HTTP_GET, [asset](AsyncWebServerRequest *request) { handleWebAsset(request, asset); });
  }
}
#endif  // TRANSIT_HAVE_WEB_ASSETS

// ---------------------------------------------------------------------------
// The Host check and the exception-globals warming, as a HANDLER rather than a middleware
// (DESIGN.md SS7, SS12.1). This replaces the single `g_server.addMiddleware(...)` registration that
// used to do both jobs, and the reason is not tidiness - it is that the middleware chain could
// reboot the device and this cannot.
//
// WHAT THE CHAIN DOES WITH ONE MIDDLEWARE IN IT. `AsyncMiddlewareChain::_runChain`
// (Middleware.cpp:56-71) builds a `std::function` `next` that captures five things including a
// COPY of the finalizer - 32 bytes, well past libstdc++'s 8-byte small-object buffer, so it is
// heap-allocated. It then calls `m->run(request, next)`, whose parameter is `ArMiddlewareNext` BY
// VALUE: a second copy, a second allocation. `AsyncMiddlewareFunction::run` then calls
// `_fn(request, next)`, whose parameter is by value again: a third. Three small allocations per
// request, and the cost is per middleware - so "merge the two middlewares into one" was not
// available as a mitigation here, because they were already one registration.
//
// WHY THAT WAS FATAL. `std::function`'s copy constructor allocates with plain `operator new`,
// which THROWS. `_runChain` has no `try`, nor does `_runMiddlewareChain` (WebRequest.cpp:1032),
// nor `_parseLine`, nor `_onData`, nor `AsyncClient::_recv`, nor `_async_service_task`. There is
// no user hook anywhere on that path. So a `std::bad_alloc` from a 32-byte allocation was
// `std::terminate` - a reboot - and the emergency exception pool and the per-task warming
// (SS12.1) could not help: they make a throw CATCHABLE, and nothing in the library catches this
// one. Observed in the 2026-09-16 device suite as a reboot during the page-cycling section:
//   __terminate <- std::terminate <- __cxa_throw <- operator new <- std::function copy
//     <- AsyncMiddlewareFunction::run <- AsyncMiddlewareChain::_runChain (Middleware.cpp:70)
//     <- _runMiddlewareChain (WebRequest.cpp:1038) <- _parseLine <- _onData <- AsyncClient::_recv
//
// WHY A HANDLER FIXES IT RATHER THAN NARROWING IT. `_runChain`'s first line is
// `if (!_middlewares.size()) return finalizer();`. With no middleware registered on the server and
// none on any handler, the whole chain is that one branch: no `std::function` is copied, no
// allocation is attempted, and the terminate site is unreachable rather than unlikely. The two
// finalizer lambdas `_runMiddlewareChain` builds capture one pointer each, which fits the
// small-object buffer and does not allocate either.
//
// AND IT RUNS EARLIER, WHICH FIXES A SECOND THING. `AsyncWebServer::_attachHandler` calls
// `canHandle()` on each handler in registration order at END OF HEADERS - before the body is
// parsed, and therefore before `handleBody`/`handleUpload`. The middleware chain runs AFTER the
// body (`_parseLine` switches to PARSE_REQ_BODY at end-of-headers and only calls
// `_runMiddlewareChain()` once the body is complete), which is why `handleOtaUpload()` had to
// repeat the Host check and the warming itself. Registered first, this handler sees every request
// before anything else does, so a DNS-rebound upload never reaches `Update.begin()` at all and the
// duplication in the OTA path is gone.
//
// THE ONE THING IT COSTS. A bad-Host request with a body now has that body read and discarded
// before the 421 goes out (`isRequestHandlerTrivial()` is left at its default `true`, so the bytes
// are counted, not parsed, and no callback sees them), where the old OTA-specific check hung up on
// the first chunk. Named rather than hidden: the property worth having is that no side effect
// happens, and none does - nothing is written to flash, nothing is allocated per chunk. Making
// `isRequestHandlerTrivial()` false to get the hang-up back would turn a hostile `text/plain` body
// into parsed form parameters, which is a worse trade.
class HostGuardHandler : public AsyncWebHandler {
 public:
  // const, and with two deliberate side effects. `_attachHandler` calls this exactly once per
  // request, on the AsyncTCP task, which makes it the earliest code of ours that runs for ANY
  // request - including one with a body.
  bool canHandle(AsyncWebServerRequest *request) const override {
    // DESIGN.md SS12.1: the AsyncTCP service task is created by the library, so we cannot warm it
    // at its entry. A task's FIRST throw allocates its per-task __cxa_eh_globals with a plain
    // malloc inside __cxa_throw and calls std::terminate() outright if that fails - past every
    // try/catch and before the emergency pool is consulted - and on this task the first throw is
    // overwhelmingly a bad_alloc, i.e. exactly when the heap is gone. Pay it here, on request
    // number one, while the heap is healthy. One pthread_getspecific per request thereafter.
    transit_app::warmExceptionGlobals("async_tcp");
    // Refresh the in-flight count here as well as at accept. Requests finish between connections,
    // and this is the only other place that runs on the AsyncTCP task for every request - without
    // it the poller's job gate would read a count that only ever moved when a NEW connection
    // arrived. Allocates nothing (admission control, above).
    sweepInFlight();
    // Claims the request only when the Host is NOT one of ours, so the real routes are reached
    // exactly as before. hostAllowed() allocates nothing and cannot throw (host_match.h), which is
    // what makes it safe to call from here: an exception escaping canHandle() would unwind into
    // _parseLine, where there is no catch, which is the failure this whole class removes.
    return !hostAllowed(request);
  }

  void handleRequest(AsyncWebServerRequest *request) override {
    // A fixed literal rather than sendError()'s JsonDocument + String: this answer has to go out
    // when the heap is momentarily exhausted, the same reasoning as sendFailure().
    sendUnderPressure(request, 421, "{\"error\":\"this device is not reachable under that host name\"}");
  }
};

}  // namespace

// Every handler runs on the AsyncTCP task and copies a Config (strings, vectors) or builds a
// JsonDocument; with -fexceptions on, a bad_alloc there that nothing catches is std::terminate and
// a reboot. Under the 2026-09-15 device suite's request storms that happened while the poller held
// the heap. Wrapped, the request gets a 503 and the browser retries on its next tick.
ArRequestHandlerFunction guarded(ArRequestHandlerFunction fn) {
  return [fn](AsyncWebServerRequest *request) {
    try {
      fn(request);
    } catch (const std::bad_alloc &) {
      // THE CRASH THIS LINE CAUSED, and now does not (coredump, 2026-09-17, heap_reserve.h): the
      // catch handler was `request->send(503, ...)`, and send() allocates - beginResponse() does
      // `new AsyncBasicResponse(...)`, sz=100 in the dump, plus two Strings. With the heap gone
      // that second allocation threw too, out of a catch handler with nothing outside it, which is
      // std::terminate. sendUnderPressure() frees the 1 KB reserve first and wraps the send in a
      // nested try/catch, which IS legal inside a handler.
      sendUnderPressure(request, 503, "{\"error\":\"out of memory, retry\"}");
    }
  };
}

void startWebServer(std::function<void(bool)> onConfigChanged) {
  setHostName(getActiveConfig().device.name);

  // THE SERVER'S MIDDLEWARE CHAIN IS DELIBERATELY EMPTY. See HostGuardHandler above: this used to
  // be `g_server.addMiddleware(...)`, and that one registration was an uncatchable reboot path.
  // Nothing may add one back without reading that comment first.
  g_server.addHandler(new HostGuardHandler());  // FIRST: _attachHandler takes the first match

  g_server.on("/api/state", HTTP_GET, guarded(handleGetState));
  g_server.on("/api/config", HTTP_GET, guarded(handleGetConfig));
  g_server.on("/api/config", HTTP_PUT, [onConfigChanged](AsyncWebServerRequest *request, JsonVariant &json) { handlePutConfig(request, json, onConfigChanged); });
  g_server.on("/api/pin", HTTP_POST, [](AsyncWebServerRequest *request, JsonVariant &json) {
    try {
      handlePostPin(request, json);
    } catch (const std::bad_alloc &) {
      sendUnderPressure(request, 503, "{\"error\":\"out of memory, retry\"}");
    }
  });
  g_server.on("/api/reboot", HTTP_POST, guarded(handlePostReboot));
  // Test hooks (DESIGN.md SS7): what the screen is doing, and a simulated touch.
  g_server.on("/api/debug/ui", HTTP_GET, guarded([](AsyncWebServerRequest *request) {
    ui::UiDebug d = ui::debugSnapshot();
    JsonDocument doc;
    doc["page"] = d.page;
    doc["dimmed"] = d.dimmed;
    doc["brightness"] = d.brightness;
    doc["due_active"] = d.due_active;
    doc["chimes"] = d.chimes;
    doc["active_profile"] = d.active_profile;
    JsonArray shown = doc["shown_stops"].to<JsonArray>();
    for (const std::string &k : d.shown_stops) shown.add(k);
    JsonArray hidden = doc["hidden_panels"].to<JsonArray>();
    for (const std::string &k : d.hidden_panels) hidden.add(k);
    doc["ticker"] = d.ticker;
    doc["rows"] = d.rows;
    doc["header_weather"] = d.header_weather;
    // LVGL's static pool (lv_conf.h LV_MEM_SIZE), not the ESP heap. lv_total is what TLSF reports
    // as usable; lv_max_used is the high-water since boot, the number that says whether a page
    // cycle ever came close to the ceiling. lv_page_cost is what each page's last build took -
    // main, night, stats, device - and lv_page_refusals counts the builds the pool would not take
    // (the device stayed where it was instead; DESIGN.md SS8).
    doc["lv_used"] = d.lv_used;
    doc["lv_free"] = d.lv_free;
    doc["lv_max_used"] = d.lv_max_used;
    doc["lv_total"] = d.lv_total;
    doc["lv_frag_pct"] = d.lv_frag_pct;
    doc["lv_page_refusals"] = d.page_refusals;
    doc["lv_tight"] = d.pool_tight;  // the page that is up left under ~3 KB: it works, but only just
    // DESIGN.md SS5/SS12.1: reads the display task made on another task's state that found the lock
    // busy and redrew last frame's value. The display task never waits for a lock, so this is what
    // that costs. It should creep, not climb.
    doc["lock_misses"] = d.lock_misses;
    doc["tick_ms"] = d.tick_ms;
    doc["tick_ms_max"] = d.tick_ms_max;
    // DESIGN.md SS12.1: the longest the poller task has run a CPU-bound loop without letting IDLE0
    // in, since boot. The task watchdog panics the board at 5,000; cpu_yield.h aims for 40. This is
    // the observable that keeps "do not starve IDLE0" a rule with a number attached instead of a
    // convention that comes back as a backtrace.
    doc["cpu_stretch_ms_max"] = cpuStretchMsMax();
    JsonObject costs = doc["lv_page_cost"].to<JsonObject>();
    costs["main"] = d.page_cost[0];
    costs["night"] = d.page_cost[1];
    costs["stats"] = d.page_cost[2];
    costs["device"] = d.page_cost[3];
    doc["hor_res"] = d.hor_res;
    doc["ver_res"] = d.ver_res;
    doc["heap"] = ESP.getFreeHeap();
    doc["largest_block"] = heap_caps_get_largest_free_block(MALLOC_CAP_8BIT);

    // ---- The heap instrument (diag branch, 2026-09-17) ---------------------------------------
    // `heap` above stays ESP.getFreeHeap() because clients parse it, and it is MALLOC_CAP_INTERNAL:
    // it includes ~33.7 KB of 32-bit-word-only IRAM heap that malloc() will never hand out for a
    // buffer or a string, so it sits beside an 8-bit largest_block reading two different heaps.
    // heap_8bit is the one that can be compared with largest_block, and min_free8 is how close the
    // board has ever come to nothing at all - a value the trace ring cannot show, because the
    // trough may fall between two stages.
    doc["heap_8bit"] = (uint32_t)heap_caps_get_free_size(MALLOC_CAP_8BIT);
    doc["min_free8"] = (uint32_t)heap_caps_get_minimum_free_size(MALLOC_CAP_8BIT);
    // The allocator's own view of the same heap (0.3.2-rc1). `free_blocks` against
    // `largest_free_block` is the fragmentation figure this device has never had: 40 KB free in
    // one piece and 40 KB free in thirty pieces read identically on every other line here, and it
    // is the difference between a healthy board and the one that spent 2026-09-17 refusing every
    // allocation over 3,444 B. `total_blocks` rising while `allocated_blocks` does not is the
    // signature of a heap being cut up rather than filled up.
    {
      multi_heap_info_t hi;
      heap_caps_get_info(&hi, MALLOC_CAP_8BIT);
      JsonObject h8 = doc["heap8_info"].to<JsonObject>();
      h8["total_free_bytes"] = (uint32_t)hi.total_free_bytes;
      h8["total_allocated_bytes"] = (uint32_t)hi.total_allocated_bytes;
      h8["largest_free_block"] = (uint32_t)hi.largest_free_block;
      h8["minimum_free_bytes"] = (uint32_t)hi.minimum_free_bytes;
      h8["allocated_blocks"] = (uint32_t)hi.allocated_blocks;
      h8["free_blocks"] = (uint32_t)hi.free_blocks;
      h8["total_blocks"] = (uint32_t)hi.total_blocks;
    }
    // What the long-lived structures are holding (net_poller.h MemorySizes). The schedule and
    // alerts caches are the only two things here that legitimately keep data across cycles, so
    // they are the only two that could legitimately grow - which makes them the first place to
    // look when the resting floor drifts.
    {
      MemorySizes ms = getMemorySizes();
      doc["sched_cache_bytes"] = ms.sched_cache_bytes;
      doc["alerts_cache_bytes"] = ms.alerts_cache_bytes;
      doc["snapshot_bytes"] = ms.snapshot_bytes;
      doc["retained_slots"] = ms.retained_capacity;
      doc["tv_slots"] = ms.tv_capacity;
    }
    doc["uptime_s"] = (uint32_t)(millis() / 1000);
    doc["reset_reason"] = (int)esp_reset_reason();  // 3 = SW restart, i.e. a self-heal reboot
    // How many published Snapshots are alive (net_poller.h). Since the publish became a move it is
    // ONE between publishes and TWO for up to a second after one, while the display task's
    // last-good reference still names the outgoing Snapshot. It read three before that change (the
    // poller's working value, the published copy, and the display's). Above two, or climbing, is a
    // reference nobody is releasing.
    doc["snapshots_live"] = snapshotsLive();
    doc["failed_polls"] = failedPolls();
    doc["wedged_polls"] = wedgedPolls();  // the non-throwing wedge tally; 15 reboots the board
    // The OOM tally and which rule is currently saying something (wedge_policy.h). THREE
    // consecutive out-of-memory cycles reboot, counted from the catch sites rather than re-derived
    // from a heap reading afterwards - the correction that came out of the 2026-09-17 wedge, where
    // the old rule would have taken fifty-one minutes to fire because a failed poll backs the
    // interval off to 240 s.
    doc["oom_streak"] = oomStreak();
    doc["wedge_reason"] = wedgeReason();
    doc["oom_polls_before_reboot"] = (uint32_t)kOomPollsBeforeReboot;
    doc["proxy_queue_depth"] = proxyQueueDepth();  // pinned at 2 = the audit's stuck-queue wedge
    // Error replies that could not be built at all and ended in a closed connection instead
    // (heap_reserve.h). Should be zero; a number that moves means the heap reached a state where
    // even a fixed-literal 503 would not fit, which is the state that used to reboot the board.
    doc["oom_replies_dropped"] = oomRepliesDropped();
    doc["heap_reserve_held"] = heapReserveHeld();
    // The Bluetooth-memory release, proved rather than inferred (heap_reserve.h, main.cpp).
    // `bt_release_rc` is esp_bt_mem_release()'s esp_err_t - 0 is ESP_OK, -1 means it was never
    // called - and `bt_release_gain_bytes` is the MALLOC_CAP_8BIT free-heap delta across the call,
    // which is what says whether libbt's 4,464 B really joined the heap.
    doc["bt_release_rc"] = bluetoothReleaseRc();
    doc["bt_release_gain_bytes"] = bluetoothReleaseGainBytes();
    // Admission control (admission.h). `in_flight` is how many AsyncWebServerRequest objects are
    // alive; `admission_refusals` counts connections closed at accept because the cap or a heap
    // floor said no. A refusal is a working defence, not a fault - but a number that climbs while
    // nobody is bursting means a floor is too high or the sweep is not seeing completions.
    doc["in_flight_requests"] = inFlightRequests();
    doc["admission_refusals"] = admissionRefusals();
    doc["max_in_flight_requests"] = (uint32_t)kMaxInFlightRequests;
    // The shared poll scratch (net_poller.h ScratchStats, DESIGN.md SS5). `scratch_max_bytes` is
    // the largest response body this device has ever buffered - the measurement that says whether
    // the 6,144 B reservation is the right size at all, which nothing could previously answer.
    // `scratch_grows` counts the bodies that went past the reservation; it should settle at a
    // small number and then stop moving, because the reservation ratchets up to them rather than
    // being handed back and retaken every cycle.
    {
      ScratchStats ss = getScratchStats();
      doc["scratch_max_bytes"] = ss.max_bytes;
      doc["scratch_reserve_bytes"] = ss.reserve_bytes;
      doc["scratch_capacity"] = ss.capacity;
      doc["scratch_grows"] = ss.grows;
    }
    // Bytes of stack each task has never gone below. Rules a stack that has quietly eaten into the
    // heap in or out before any of the heap numbers are interpreted.
    JsonObject hwm = doc["stack_hwm"].to<JsonObject>();
    hwm["loopTask"] = taskStackHwm("loopTask");
    hwm["async_tcp"] = taskStackHwm("async_tcp");
    hwm["net_poller"] = taskStackHwm("net_poller");
    // The ring. ?since=<trace_seq from the last sample> returns only what is new, which is what a
    // sampler should use; ?n=1..32 caps the rows; ?stages=1 adds the id->name table (left out of
    // the routine sample because it is ~300 B of body that never changes).
    uint32_t first_seq = 0;
    size_t rows = 0;
    const uint32_t since = queryU32(request, "since", 0);
    if (request->hasParam("log")) {
      // ?log=1: the per-cycle memory log (cycle_log.h) INSTEAD of the stage trace, because the two
      // share a render buffer and are never wanted in the same breath. ?since=<cycle_log_seq> and
      // ?n=1..40 work the same way. Two hours of history at a 30 s cadence, which is what the
      // 64-entry stage ring - three cycles - cannot give.
      doc["cycle_log"] = serialized(renderCycleLog(since, (size_t)queryU32(request, "n", kCycleLogMaxRows), &first_seq, &rows));
      doc["cycle_log_first"] = first_seq;  // sequence number of cycle_log[0]; > since means it wrapped
      doc["cycle_log_rows"] = (uint32_t)rows;
      doc["cycle_log_cap"] = (uint32_t)kCycleLogCap;
    } else {
      doc["trace"] = serialized(renderTrace(since, (size_t)queryU32(request, "n", kTraceMaxRows), &first_seq, &rows));
      doc["trace_first"] = first_seq;  // sequence number of trace[0]; > since means the ring wrapped
      doc["trace_rows"] = (uint32_t)rows;
    }
    doc["cycle_log_seq"] = cycleLogSeq();  // pass this back as ?log=1&since= next time
    doc["trace_seq"] = heapTraceSeq();  // pass this back as ?since= next time
    if (request->hasParam("stages")) {
      JsonArray stages = doc["trace_stages"].to<JsonArray>();
      for (size_t i = 0; i < kHeapTraceStageCount; i++) stages.add(kHeapTraceStages[i]);
    }
    sendJson(request, 200, doc);
  }));
  g_server.on("/api/debug/tap", HTTP_POST, guarded([](AsyncWebServerRequest *request) {
    if (!requirePin(request)) return;  // it changes what the screen shows, so it is state-changing
    ui::requestTap();
    request->send(200, "application/json", "{\"ok\":true}");
  }));
  // POST /api/debug/page?page=main|night|stats|device (or the same word as the whole body): drive
  // the page cycle from the LAN without a finger on the panel. It exists because the LVGL pool is
  // the one thing the native simulator cannot reproduce - firmware/sim builds with a 512 KB
  // LV_MEM_SIZE for 64-bit pointers - so the peak a page transition reaches has to be measured on
  // the hardware, and that needs thirty cycles, not thirty taps. ui::requestPage() only sets a
  // flag the LVGL task reads in tick(); nothing here touches an lv_obj from the web server task.
  g_server.on("/api/debug/page", HTTP_POST, guarded([](AsyncWebServerRequest *request) {
    if (!requirePin(request)) return;  // it changes what the screen shows, like /api/debug/tap
    std::string page;
    if (request->hasParam("page")) {
      page = request->getParam("page")->value().c_str();       // ?page=stats
    } else if (request->hasParam("page", true)) {
      page = request->getParam("page", true)->value().c_str();  // page=stats as a form field
    } else if (request->_tempObject != nullptr) {
      page = (const char *)request->_tempObject;                // a raw body, from the handler below
    }
    if (!ui::requestPage(page)) {
      sendError(request, 400, "page must be main, night, stats or device", "page");
      return;
    }
    request->send(200, "application/json", "{\"ok\":true}");
  }), nullptr, [](AsyncWebServerRequest *request, uint8_t *data, size_t len, size_t index, size_t total) {
    // A raw body ("stats"), which is what curl -d sends. It is only PARSED here - the PIN check
    // lives in the handler above, which runs after this, and applying the page from an unchecked
    // body would be an auth bypass. Short by construction, so one chunk is the only case worth
    // handling; _tempObject is free()d with the request by ESPAsyncWebServer.
    if (index != 0 || len != total || len == 0 || len > 16 || request->_tempObject != nullptr) return;
    char *buf = (char *)malloc(len + 1);
    if (buf == nullptr) return;
    size_t n = 0;
    for (size_t i = 0; i < len; i++) {
      char c = (char)data[i];
      if (c == '\n' || c == '\r' || c == ' ') continue;
      buf[n++] = c;
    }
    buf[n] = '\0';
    request->_tempObject = buf;
  });
  g_server.on("/api/debug/oom", HTTP_POST, guarded(handleDebugOom));  // SS12.1 exception-pool proof; PIN-gated
  g_server.on("/api/wifi/reset", HTTP_POST, guarded(handlePostWifiReset));

  g_server.on("/api/proxy/stops", HTTP_GET, guarded(handleProxyStops));
  g_server.on("/api/proxy/schedule", HTTP_GET, guarded(handleProxySchedule));
  g_server.on("/api/rail/stations", HTTP_GET, guarded(handleRailStations));
  startProxyWorker();

  // Registered before /api/stats: ESPAsyncWebServer matches handler URIs by prefix, so the
  // longer path has to come first or handleGetStats answers it with "stop is required".
  g_server.on("/api/stats/overview", HTTP_GET, guarded([](AsyncWebServerRequest *request) {
    // The same entry gate the other heavy reads take (refuseIfLowHeap). This endpoint needed MORE
    // memory than /api/state and had no gate at all, so on a low heap it degraded into silence -
    // the request was queued, paused (which turns its server-side timeout off) and never reached,
    // and the client waited until IT gave up (audit_runtime SS4). A prompt 503 is the right answer.
    if (refuseIfLowHeap(request)) return;
    int days = request->hasParam("days") ? atoi(request->getParam("days")->value().c_str()) : 7;
    queueOverviewRequest(request, days);
  }));
  g_server.on("/api/stats", HTTP_GET, guarded(handleGetStats));
  g_server.on("/api/log/index", HTTP_GET, guarded(handleLogIndex));
  // "/api/log/<file>.csv" - matched with a regex-free prefix check in onNotFound below instead of
  // a wildcard pattern, to keep the matcher simple.

  g_server.on("/api/ota", HTTP_POST, handlePostOta, handleOtaUpload);

#ifdef TRANSIT_HAVE_WEB_ASSETS
  registerWebAssets();
#else
  g_server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/plain", "web UI not built into this firmware (web/build.mjs never ran) - try /api/state");
  });
#endif

  g_server.onNotFound(guarded([](AsyncWebServerRequest *request) {
    if (request->url().startsWith("/api/log/") && handleLogDownload(request)) {
      return;
    }
    request->send(404, "application/json", "{\"error\":\"not found\"}");
  }));

  g_server.begin();
  log_i("web_server: listening on port 80");
}

bool otaBusy() { return g_ota.busy; }

// Reboots shortly after the current request's response has had a chance to go out - calling
// ESP.restart() directly inside the handler risks cutting the HTTP response off mid-flight.
// Declared in web_server.h since 0.3.2-rc1 so main.cpp's nightly restart can use the same path
// (nightly_restart.h): it has no response to protect, but it wants the same grace for whatever
// the poller or the display task happens to be in the middle of.
void scheduleRestart() {
  xTaskCreate(
    [](void *) {
      vTaskDelay(pdMS_TO_TICKS(300));
      ESP.restart();
    },
    "restart", 2048, nullptr, 1, nullptr
  );
}

uint32_t inFlightRequests() { return g_in_flight_count.load(std::memory_order_relaxed); }

uint32_t admissionRefusals() { return g_admission_refusals.load(std::memory_order_relaxed); }

}  // namespace transit_app
